### ISSUE TITLE
Investigate caching issue

### ISSUE THREAD

**Issue by Aprillion** [StampyAI/stampy-ui#106]
We discovered that cache refresh doesn't work - e.g. for https://ui.stampy.ai/?state=8241_ (=> KV key 8241 in https://dash.cloudflare.com but CF doesn't show metadata of KV records, so I couldn't quickly check whether here is a problem in expiration date format for that particular record, for all records, or something else)

I cleared the KV store records as a quick fix, but need to follow up on the investigation when I (or someone) have more time.

Ideas that could help to prevent hard-to-debug caching issues in the future:
* move timing info from metadata to KV value itself (to make it inspectable in dashboard)
* add Remix API route to clear the cache (and maybe redirect to homepage in order to prime the cache at this point for fast initial load for the next user)
* replace the stale version we display in UI when a new version of page is loaded on the server (do not require manual reload)
* try to reproduce with some Test question:
   * load page
   * edit page on wiki
   * wait for the stale time (ideally decrease on localhost from 10 minutes to 10 seconds for this investigation)
   * reload page
   * check logs/debugger - did we fetch a new version in the worker and update the cache?
  
...and if is the problem reproducible even on localhost, let's fix it 🤞

**Comment by Aprillion** [comment]
I added https://ui.stampy.ai/questions/cache endpoint to see all KV store metadata and all timestamps are from October 18 => refreshing data in the background does not work, seems like real CF workers kill the background requests, and it only ever worked on localhost (using `wrangler` and `miniflare` to simulate workers as recommended by CF, but there are differences it seems).

So... if I want to refresh in the background, I have to make the request from browser (and I guess I should replace the content once the new content is loaded).

Workaround until fixed = manually load https://ui.stampy.ai/?reload (but it only works for homepage at the moment unfortunately)

**Comment by Aprillion** [comment]
I haven't heard @plexish run around and scream about any new caching issues, not even after https://www.lesswrong.com/posts/fSMrwJnqRb5NrMYFx/all-agi-safety-questions-welcome-especially-basic-ones-2 ..

Checking https://ui.stampy.ai/questions/cache, there were still some left-over static assets I investigated in #110, #111, #112, but the redirect is removed and I didn't experience troubles since, so cleared the cache and will optimistically hope that I won't see any static assets on that page in the future (and if yes, I will open a new issue to follow up on that investigation)

**Comment by Aprillion** [comment]
ok, I was an idiot and I stored wrong KV key in GH secret - it must be the one for `STAMPY_KV` namespace, and I copy&🍝 the one for `__stampy-ui-workers_sites_assets` 16 days ago - the one with all the static files 🙈

now fixed (for real this time, right?!? 🥵)

**Comment by ccstan99** [comment]
Aah, that makes a lot more sense! I was wondering how all those static files got into the STAMPY_KV and didn't see how JSON.parse would "cause" it. With the new `cleanCache()` function, hopefully you won't need to muck around with the GH secrets anymore.
