### ISSUE TITLE
Consider a two-column layout

### ISSUE THREAD

**Issue by ChrisRimmer** [StampyAI/stampy-ui#115]
A pair of common complaints in software (and especially web systems!) are inadequate usage of horizontal display space, and _over-use_ of vertical space, by stacking a header and content and footer in the middle of the display and taking up what should arguably be space better given to content.

Obviously on narrow displays, the current layout we use is more or less compulsory, but on wider displays we might imagine taking the header, search, and footer, and pulling them horizontally out of the main content column, freeing screen real estate for the thing we care about most and maximising how much the user can see, while also retaining easy access to things like the search box which currently requires a long and attention-breaking scroll to the top of the page for anyone who has opened a lot of questions.

Very roughly, this could be achieved with some fairly basic CSS flex rules and specifying some minimum widths on the two colums so that they naturally stack into a narrow-screen-friendly layout, or perhaps more "correctly" with some CSS grid rules, though I'm not as familiar with how that works so can't speculate to the implementation details.

**Comment by plexish** [comment]
I think one column is probably the right way to stay, and two column would feel cluttered on anything but extremely wide monitors? @ccstan99, what's your take?

**Comment by Aprillion** [comment]
I am going to use my gatekeeping powers and put a stop on this issue for now. If anyone really wants this, I am fine with a PR that would introduce the for non-fun version of stampy or behind a feature flag (e.g. in URL `...&multiColumn`), but I don't want it as default for fun-logo version and keeping multiple versions would add complexity, so let's not attract discussion about it by keeping an open issue - let's please consider it only if more people request it independently.
