### ISSUE TITLE
Render answers from Google Docs / Coda

### ISSUE THREAD

**Issue by Aprillion** [StampyAI/stampy-ui#123]
We are moving our "database" of questions and answers from MediaWiki to Coda and GDocs...

First step for the UI is to render a test document, e.g. let's try the [export](https://docs.google.com/feeds/download/documents/export/Export?exportFormat=html&id=10g6U9SL0CBy__wCBTib7_WhB3S3aaFt7Fx1vVgCzg2I) feature
* we decided to read `Rich Text` markdown field from Coda, so we don't need to merge rendering directly from GDoc

**Comment by Aprillion** [comment]
exploring Coda: https://coda.io/developers/apis/v1#tag/Tables, and looks like GET requests work from browser when I am logged in to UI

list of tables in our doc id: https://coda.io/apis/v1/docs/fau7sl2hmG/tables
Initial questions:  https://coda.io/apis/v1/docs/fau7sl2hmG/tables/Initial%20questions/rows?valueFormat=simpleWithArrays&useColumnNames=true

filter by tag: https://coda.io/apis/v1/docs/fau7sl2hmG/tables/Answers/rows?valueFormat=simpleWithArrays&useColumnNames=true&query=Tags:%22superintelligence%22
filter by status: https://coda.io/apis/v1/docs/fau7sl2hmG/tables/Answers/rows?valueFormat=simpleWithArrays&useColumnNames=true&query=Status:%22Live%20on%20site%22

**Comment by Aprillion** [comment]
I added `CODA_TOKEN` to https://github.com/StampyAI/stampy-ui/settings/secrets/actions while writing README instructions for local development with Coda.

**Comment by Aprillion** [comment]
the new `canonically answered canonical questions` list is 99.9% going to be https://coda.io/d/AI-Safety-Info_dfau7sl2hmG/Aiming-for-Exceptional_suCgH#_lu0xQ

**Comment by ccstan99** [comment]
Thanks for keeping these helpful notes for getting "up to speed" on Coda!

It looks like the Manage answers view includes all canonical questions even if they don't have canonical answers yet (see rows 1-24) that have Status like "Not started", "In progress", "In review", etc. So it probably still needs to get filter/queried by Status as "Live on site"?

**Comment by Aprillion** [comment]
I will leave it up to @plexish to explain, he had some half-baked notes on Discord that made me feel I understand the intention, but I am not sure any more 🤔

**Comment by plexish** [comment]
Hi!

_Manage answers_ (should probably be renamed _All answers API_, will doing that break things @Aprillion? or is it queried by table ID?) is meant as the big table with most of the information on all of the answers, _Answers_ is the megatable with virtually all the columns. There are other tables for various subsets of answers, which are editor and reviewer interfaces.

It might be best to have all the UI API stuff talking to one coda view and filtering in the query, to reduce the number of places coda changing could break the UI, which would point towards using Manage answers. Unless there's a significant penalty for querying an unfiltered table, in which case.. probably we want to make subpages of Manage answers with each view that we want to talk to over the API? I've set up an example here: https://coda.io/d/AI-Safety-Info_dfau7sl2hmG/On-site-API_su5gl#On-site-answers-API_tu_mN/r161 with the table "On-site answers API" to compare.

Very happy to make more views or teach people how easy it is to do them on coda :)

**Comment by Aprillion** [comment]
I prefer to fetch by table name, thus rename would break things if we were already in production, but we aren't in production yet, so still time to rename everything without too much trouble, just tell me via Discord when you do.

API does not support filtering by more than 1 criteria (as far as I could tell few days ago .. they might add such feature one day), and fetching big-ass tables with all columns might not scale in the future if we have more thousands of records - though that way should be fine for "beta" I guess.

When we switch the production to Coda, any changes in table will have to be more controlled - ideally by creating new view, testing it in non-prod environment, then switching to new view by renaming the old one with some `_old` suffix and renaming the new one to the official name used by UI.

**Comment by plexish** [comment]
Okay, that makes sense. We can stabilize column names before prod, and make views in coda with not too many columns for each API call we want
