### ISSUE TITLE
Replace header and footer links to wiki with links to coda

### ISSUE THREAD

**Issue by Aprillion** [StampyAI/stampy-ui#128]
Let's replace wiki links from header and footer:
* Get Involved is publicly accessible on Coda => https://coda.io/d/AI-Safety-Info-Dashboard_dfau7sl2hmG/Get-involved-with-AI-Safety-Info_susRF
* About => ?
* Join Discord => ?
* Copyrights => ?

**Comment by Aprillion** [comment]
Specification from plex on Discord:
```html
      <footer>
        <a href="https://discord.gg/vjFSCDyMCy">Join Discord</a>
        <a href="https://get_involved.aisafety.info/">About / Get Involved</a>
        <a href="https://dashboard.aisafety.info/">Dashboard</a>
        <a href="https://github.com/StampyAI/stampy-ui">Help Code</a>
        <a href="https://docs.google.com/forms/d/e/1FAIpQLSdT--8lx5F2pAZoRPPkDusA7vUTvKTVnNiAb9U5cqnohDhzHA/viewform">
          Feedback
        </a>
        <a href="https://coda.io/d/AI-Safety-Info-Dashboard_dfau7sl2hmG/Copyright_su79L#_luPMa">@ 2022 stampy.ai</a>
      </footer>
```

With note: `Not settled on using the redirects I set up` but let's use that for now.

**Comment by plexish** [comment]
> Specification from plex on Discord:
> 
> ```
>       <footer>
>         <a href="https://discord.gg/vjFSCDyMCy">Join Discord</a>
>         <a href="https://get_involved.aisafety.info/">About / Get Involved</a>
>         <a href="https://dashboard.aisafety.info/">Dashboard</a>
>         <a href="https://github.com/StampyAI/stampy-ui">Help Code</a>
>         <a href="https://docs.google.com/forms/d/e/1FAIpQLSdT--8lx5F2pAZoRPPkDusA7vUTvKTVnNiAb9U5cqnohDhzHA/viewform">
>           Feedback
>         </a>
>         <a href="https://coda.io/d/AI-Safety-Info-Dashboard_dfau7sl2hmG/Copyright_su79L#_luPMa">@ 2022 stampy.ai</a>
>       </footer>
> ```
> 
> With note: `Not settled on using the redirects I set up` but let's use that for now.

Had to drop dashboard.aisafety.info to stay within the page rules limits, so that'll need to be removed or replaced with one on a different domain, but otherwise this is done.

**Comment by Aprillion** [comment]
Updated dashboard link in `future` branch too.
