### ISSUE TITLE
Add tags to questions

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#14]
https://www.figma.com/proto/gm06d1l5stMlnKxeElWBEc/Stampy-AI-Alignment-FAQ?node-id=116%3A415&scaling=min-zoom&page-id=116%3A414&starting-point-node-id=116%3A415

Should pull from column `Tags`  [on coda,](https://coda.io/@alignmentdev/ai-safety-info/on-site-api-65) and not display any tags [marked as Internal in coda](https://coda.io/@alignmentdev/ai-safety-info/tags-57).

Enables #15

**Comment by ChrisRimmer** [comment]
Quick note from Stampy Dev call 2022-11-13

The Wiki does have tags for articles / questions so this data does exist to connect to the UI
