### ISSUE TITLE
Clicking the edit pencil for the first time does not always take you to the Gdoc, instead moves the question to the top

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#152]
Open any of the questions other than the first on https://aisafety.info/ and click edit to test.

**Comment by plexish** [comment]
hm, seems to be working now, hopefully fixed rather than eigenbug

**Comment by Aprillion** [comment]
I didn't change anything myself, but we merged a few PRs, so maybe some intermediate state 🤞 Let's close for now and reopen if it happens again (ideally with repro steps, but even if it will happen without explanation)
