### ISSUE TITLE
Switch stampy.ai main domain to point to the UI

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#157]

**Comment by Aprillion** [comment]
I need @plexish  to give me CloudFlare Dashboard permission to also edit Worker settings, not just page settings..

And @MatthewBaggins will remove the dependency on wiki from https://github.com/StampyAI/stampy repo (it assumed wiki lives on top domain and stampy didn't even start when I tried to switch the top domain earlier today)

**Comment by Aprillion** [comment]
so, https://stampy.ai works now, but I want to use the "fun logo" version by default

I tried to make https://www.stampy.ai redirect to top domain, while keeping https://wiki.stampy.ai pointing to the wiki, but looks like it's either one or the other or none of those, but not both  ¯\\\_(ツ)_/¯

**Comment by plexish** [comment]
We can lose the wiki. Having the right logo on Stampy is more important
