### ISSUE TITLE
Gracefully handle unknown questions

### ISSUE THREAD

**Issue by mruwnik** [StampyAI/stampy-ui#164]
If someone manually inputs the id of an non existent question (e.g. https://aisafety.info/?state=ZZZZ), the UI will keep showing that it's loading:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/3942390/219382033-f402d7b2-0fd5-4972-b143-6cf224feb0bb.png">

# Suggested fixes:
* ignore it and remove it from the URL - this is iffy, as it's magical and looks like a bug
* ignore it and just don't display an entry for that page id - also iffy, for the same reason
* display some kind of error message - this is nice in so far as it's explicit, but can result in clutter

**Comment by plexish** [comment]
Agree with the analysis, I think I lean towards option 3. Something like _No question found with ID $1. Please go to the Discord in the lower right and report where you found this link._
