### ISSUE TITLE
Log all searches

### ISSUE THREAD

**Issue by mruwnik** [StampyAI/stampy-ui#174]
It would be useful to have a collection of what gets searched.
* saved to coda?
* cloudflare + export?

**Comment by ccstan99** [comment]
All calls sent through the semantic search /api/search are logged as part of the Google Cloud Run. That can be exported periodically. Currently, the in-browser TF searches are not tracked. So we can either log that or wait until it gets integrated with the /api/search.

**Comment by mruwnik** [comment]
When is it likely to get integrated? That does sound like a much better solution, on multiple levels

**Comment by ccstan99** [comment]
I hope to have a better idea after testing out the responsiveness next weekend. If we can move it over, shouldn't take too long.

**Comment by tayler6000** [comment]
Idea approved in 26 Feb 2023 Office Hours

**Comment by diziet** [comment]
If we implement a feature like this, I would suggest logging these queries in such a way that they can not be tied to any PII (personally identifiable information) from the user and additionally create a Terms of Service and Privacy page that unambiguously and clearly to the user spells out how the data is used. The ideal storage functions would make us compliant with the variety of privacy regulation around the world. See https://github.com/StampyAI/stampy-ui/issues/81 for related discussion

**Comment by Aprillion** [comment]
@diziet if you've done some research on best TOS that we could reuse, can you please link in here? If we choose to go that way on the next dev call, it might be useful to have all info ready for implementation, thanks! ;)

**Comment by mruwnik** [comment]
can be viewed at https://console.cloud.google.com/logs/query;query=resource.type%20%3D%20%22cloud_run_revision%22%0Aresource.labels.service_name%20%3D%20%22stampy-nlp%22%0Aresource.labels.location%20%3D%20%22us-west1%22%0A%20severity%3E%3DDEFAULT%20queries;cursorTimestamp=2023-05-24T15:12:02.477604Z?project=stampy-nlp
