### ISSUE TITLE
Add comment button

### ISSUE THREAD

**Issue by mruwnik** [StampyAI/stampy-ui#176]
Add a way to add comments or clarifying questions to answers. 

This is currently possible via the edit button, as comments can be added in GDocs, but I'm guessing that most people won't know that. Adding a separate button that also directs to the document, or adding extra info (e.g. a popup) should make that easier

**Comment by plexish** [comment]
We might attach Discord threads to each answer, which would be the natural place for comments?

**Comment by mruwnik** [comment]
That would work. Though I'm guessing it would require a bot update so it:
* creates the thread
* adds the url of the thread to coda

**Comment by plexish** [comment]
@ChrisRimmer 
> I think for creating threads per-answer, while that's inside Discord and so there's a kind of conceptual link to Stampy the Discord Bot which might make people expect that behaviour to be inside him, that might actually be more appropriate to shove into the parser Google Docs monitoring system since that's the thing which already knows most about, and makes most extensive use of, Coda and Docs state

**Comment by mruwnik** [comment]
So this would simply display a link, which on clicking would open the appropriate Discord thread?

**Comment by ChrisRimmer** [comment]
That reply Plex quoted was from Discord where I wrote it without this context - without knowing (part of?) the intent was to hotlink web users into threads. I think you can hotlink to a forum thread in Discord, but for that to work the user must already be _in_ the Discord which is a possible barrier. If we'd like users to be able to submit comments, perhaps pushing them into the Doc (very doable through the Docs API, I've tested this in the past) or into Discord via the bot, would be useful.

If we'd like to link web users into Discord, I think it would be worth taking the slightly more laborious process of having such links open a "this goes to Rob Miles' AI Discord community, if you aren't already a member of it click [invite link] to join]" modal or some such. I normally argue very strongly against modals interrupting links but most of the reasons I do so don't hold here.

**Comment by tayler6000** [comment]
Discussed this in 26 Feb 2023 office hours.

We decided there should be a `Discuss on Discord` button, this button should come up with a modal saying you must join the Discord server first for the link to work and then redirect them to the thread in Discord.  This modal should have a `Do not show this again` option.
