### ISSUE TITLE
"Helpful" button

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#19]
Increment a counter in coda, don't let people submit twice without refreshing, but accept that people can mark it multiple times in different sessions as we don't have session tracking?

**Comment by ccstan99** [comment]
Like button title/tooltip should say "like question" 
Icon should be black & white by default and full cover on hover.
https://github.com/StampyAI/stampy-ui/blob/master/app/assets/icons/thumbs-up.svg
See pen icon for implementation reference.
<img width="328" alt="Screen Shot 2022-07-03 at 2 15 08 AM" src="https://user-images.githubusercontent.com/38997995/178089207-e554bb03-3f5d-45b3-ade4-b60b6ec03954.png">

**Comment by plexish** [comment]
not "Like answer"?

**Comment by ccstan99** [comment]
@plexish You're right! I fixed the instructions above.

**Comment by plexish** [comment]
Decided to go with the name of this button being "Helpful"
