### ISSUE TITLE
Modal when clicking on Google Docs links to unpublished answers

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#192]
Published answers have the nice in-UI links, but when the answer is unpublished it takes readers to the Gdoc which is a weird UX thing. Rob suggested a modal to let users know they're going to an unfinished answer.

**Comment by mruwnik** [comment]
they now show the question on site, but with a WIP prefix. Can this be closed, or should it still do a modal?

**Comment by plexish** [comment]
Probably still a modal, to warn people before they're taken to a not-yet-finished part of the site?
