### ISSUE TITLE
Search Proposal Specs

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-ui#194]
Semantic search is getting messy! Here's a doc with a draft [proposal / specification](https://docs.google.com/document/d/1ztlTb2iXoF_1OwQ5fiGfN68Qa7YE2_G_0EhIqH1goiw/) of how things should work. Please wait until we discuss and agree during office hours before trying to implement. Thanks!

I hope this is enough for discussion purposes. LMK if picture is still needed, I can try to put together a diagram.

**Comment by ccstan99** [comment]
@markovial reported using just a term it doesn't show the answers that contain that term

> E.g. Searching just 'prosaic' does not show - 'What does prosaic alignment mean?' , until I include 'what', i.e. I have to search 'what prosaic' to get the answer to show up as a result. Similiar results for other terms - e.g. 'corrigible' does not return 'what is corrigibility', until I search 'what corrigible'.
>
> Depending on how you assume people use the search bar this might be a problem. I would ususally just type in only the core term, not see a result and assume that the site does not have an answer to that question yet. Its only because I know for a fact that the answers above were for sure approved that I even bothered trying different semantics. You could lose some readers this way.

The NLP endpoint doesn't seem to have this issue. If/when the above specs are implemented, we might consider calling the NLP endpoint sooner or making it clear that pressing ENTER can "retrieve more accurate results."

**Comment by markovial** [comment]
We just had a call in which we had some 'hacky' solutions - if someone searches just one word append a 'what' to it on the back end before searching it.

Another possibility is to use regular keyword search as long as you have just one (or two) terms, and then semantic search for anything longer than that.

**Comment by ccstan99** [comment]
Semantic search isn't particularly meaningful for incomplete searches with 1 or maybe 2 terms, so both 'hacky' solutions are possible alternatives.
