### ISSUE TITLE
"Ask follow-up question" button - icon and functionality

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#20]

**Comment by ccstan99** [comment]
Follow question button title/tooltip should say "ask followup question" 
Icon should be black & white by default and full cover on hover.
https://github.com/StampyAI/stampy-ui/blob/master/app/assets/icons/comment-question.svg
See pen icon for implementation reference.
<img width="328" alt="Screen Shot 2022-07-03 at 2 15 08 AM" src="https://user-images.githubusercontent.com/38997995/178089207-e554bb03-3f5d-45b3-ade4-b60b6ec03954.png">

**Comment by plexish** [comment]
Decided to cut this planned feature.

**Comment by plexish** [comment]
Decided to cut this planned feature.

**Comment by plexish** [comment]
Decided to cut this planned feature.
