### ISSUE TITLE
Feature Request: Sticky Header + Often used items on header

### ISSUE THREAD

**Issue by markovial** [StampyAI/stampy-ui#206]
If I have been scrolling for a while I can't search new questions anymore until I scroll all the way back up. It would be useful to have a sticky header with a pesistent searchbar. Additionally it have an icon link to a FAQ on about us/stampy related questions, e.g.:

LHS : Stampy Logo only (on click return to main page)
Mid : Search
RHS : Share link, Get Involved, Help Code, discord (moved to unified place instead of bottom right)

Also I would reccomend using unified [flaticons](https://www.flaticon.com/) for everything for a more syncd and clean aesthetic.

**Comment by plexish** [comment]
I'm going to vote for a lesswrong style sticky header where if you do a small scroll up it pops up but it's not visible in taking up screen real estate while you're scrolling down. See e.g. https://www.lesswrong.com/posts/orhEa4wuRJHPmHFsR/six-plausible-meta-ethical-alternatives

**Comment by Aprillion** [comment]
FTR lesswrong style jumping headers drive me crazy, I had to write custom CSS to disable the annoying feature for myself - so I vote against jumping headers or any floating icons. Happy to be overruled if majority of stakeholders vote for it. (my vote agains infiniscoll  was also overruled - but my solution would have been to have `Show more` and `Back to top` link buttons at the bottom of the page if both features were up to me)

**Comment by markovial** [comment]
I dont really understand what you mean by 'jumping' headers. Do you mean that you would rather that they stayed on screen all the time? The main objective I had in my mind was easy access to the search for new queries.

Also by floating icons do you mean how the discord icon is currently implemented on the bottom right? If so then yeah I am against that as well. Just as it is helpful to have access to the search bar, it is similarly helpful to have constant easy access to the links from the icons which is why I suggested putting them on the bar (not as floating around somewhere on the page).

**Comment by markovial** [comment]
I was just poking around and found some icons I had in mind. I think just the black and white version which changes to one of the stampy theme colors on hover would look good on the top bar. Maybe just even a black/gray fill on hover. I'll link them here in case they are useful: [Share link icon](https://www.flaticon.com/free-icon/chain_2949553), [Discord icon](https://www.flaticon.com/free-icon/discord_2582637), [Get involved icon](https://www.flaticon.com/free-icon/teamwork_3346566), [Help code icon](https://www.flaticon.com/free-icon/support_10169803)

There are also various stamp related icons if you wanna stick to the whole stamp theme. Something like a helpful answer gets a stamp of approval, or other kinds of stamps for things like edit, tags, etc. Maybe these can be used on the playful stampy.ai version only. Here are some examples:  [Stamp helpful](https://www.flaticon.com/free-icon/evaluate_941626), [Stamp heart](https://www.flaticon.com/free-icon/stamp_9444272)

There are some animated alternatives, if you guys wanna inject a little more dynamism: [share](https://www.flaticon.com/free-animated-icon/share_6172544), [helpful](https://www.flaticon.com/free-animated-icon/like_6172539), [code](https://www.flaticon.com/free-animated-icon/responsive_8722699)

If this seems like something that is even worthwhile doing I can find more in whatever style you guys like.

**Comment by ccstan99** [comment]
LOL! I'm definitely non-ADHD but living in a house full of moderately ADHD-diagnosed people probably skews my perception.

I wasn't around for the vote but FTR, I do agree the infinite scroll feels "overactive." 

Not a big fan of the floating Discord button either but always thought it was a "requirement." Is there a reason why it can't be just another icon like the link to GitHub and Coda?

However, I'm not fundamentally opposed to sticky/fixed headers if used properly. Does the sticky header on this GitHub page bug you @Aprillion? In general, I would consider GitHub a pretty minimal distraction site. 

On a completely different note... I find the LessWrong website aesthetically pleasing but it took me **forever** to figure out how to use it. Now that you mention it, all the things popping up were cool but also rather disorienting for me.

**Comment by ccstan99** [comment]
Yes, I feel the GH sticky header works nicely and is subtle. Perhaps we can consider something along those lines with the search bar and possibly 3 icons + discord? Having the user scroll all the way back to the top feels arcane.

**Comment by plexish** [comment]
Happy to defer to cc on this
