### ISSUE TITLE
"Hide question" button - icon and functionality

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#21]

**Comment by ccstan99** [comment]
Hide button removes the current expanded question from the list. 
Title/tooltip should say "hide question from view." 
Icon should be black & white by default and full cover on hover.
https://github.com/StampyAI/stampy-ui/blob/master/app/assets/icons/eye-slash.svg
See pen icon for implementation reference.
<img width="328" alt="Screen Shot 2022-07-03 at 2 15 08 AM" src="https://user-images.githubusercontent.com/38997995/178089207-e554bb03-3f5d-45b3-ade4-b60b6ec03954.png">

**Comment by plexish** [comment]
Let's not prioritize this, or maybe not do it with the drag to clear thing and simplifying icon set being good? @ccstan99, thoughts?

**Comment by ccstan99** [comment]
It's nice to have a minimal set of buttons as a baseline. We can fold this functionality into drag & drop and easily add the button if we hear many requests for that feature.
