### ISSUE TITLE
Feature Request: Tags page

### ISSUE THREAD

**Issue by markovial** [StampyAI/stampy-ui#212]
A page where I can see all the current existing tags so that I can click on one of them and only see the questions that have that tag. Currently I have to manually search to find a question that might potentially have the tag that I am thinking about and then click on it.

**Comment by plexish** [comment]
@markovial could you link the page which you said looks similar to what you're thinking?

**Comment by markovial** [comment]
I lost the link... Is there a way to recover links from Discord voice calls? Basically, I was just thinking of some big buttons with flaticons as a visual indicator and the name of the tag.

**Comment by plexish** [comment]
@markovial those channel's history should be saved, but I'm not seeing the relevant message by you for some reason

**Comment by markovial** [comment]
![image](https://user-images.githubusercontent.com/52564817/236704885-89c82934-5272-4cc3-8624-397b00cce82d.png)


Found it. Here is [a link](https://wordpress-theme.spider-themes.net/ama/home-classic/
) to a live website preview version. Basically it involves a card that has : a flaticon + tag name + number of items for that tag
