### ISSUE TITLE
WIP questions showing as related

### ISSUE THREAD

**Issue by robertskmiles** [StampyAI/stampy-ui#214]
At this URL
https://aisafety.info/?state=1001_
there are WIP follow up questions show up underneath.

**Comment by Aprillion** [comment]
🤔 so, the API we use to fetch question details https://coda.io/apis/v1/docs/fau7sl2hmG/tables/Answers/rows?useColumnNames=true&sortBy=natural&valueFormat=rich&query=%22UI%20ID%22:%221001%22 doesn't have any info about status of related questions... let me see if I can wait for loading that info before showing related questions
