### ISSUE TITLE
"Link to this question" button - icon and functionality

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#22]

**Comment by ccstan99** [comment]
Link button copies a link to clipboard to direct question. 
Title/tooltip should say "copy link to question." 
Icon should be black & white by default and full cover on hover.
https://github.com/StampyAI/stampy-ui/blob/master/app/assets/icons/link.svg
See pen icon for implementation reference.
<img width="328" alt="Screen Shot 2022-07-03 at 2 15 08 AM" src="https://user-images.githubusercontent.com/38997995/178089207-e554bb03-3f5d-45b3-ade4-b60b6ec03954.png">

**Comment by plexish** [comment]
Would it maybe make sense to have this appear just to the right of the question bar, rather than alongside the action icons, @ccstan99?

**Comment by ccstan99** [comment]
Maybe. I've seen the convention of a link icon appearing when you hover next to a section heading. What slightly complicates it for our situation would be to clarify between expand/collapse (right now is enabled for entire question button) vs link (maybe a smaller icon/button? would you want icon always visible?)

**Comment by plexish** [comment]
I was imagining it would be not inside the question bar, but just to the right off the edge of the bar fading into view as you hover?

**Comment by Aprillion** [comment]
Would we have 2 action bars? One below the answer after expanding and one to the right (of left?) of the question title fading into view on hover on desktop and "something else" on mobile? Not sure...

I would rather keep all actions in 1 place and have only few buttons for visitors and more for editor mode after login.

**Comment by plexish** [comment]
I'm not wedded to having it to the right, but it does feel a little like a more natural place for that action for some reason.

**Comment by ccstan99** [comment]
"fading into view as you hover"? Not sure I'm visualizing this correctly. Do you mean on the solid (white/dark) background or on the question block/button (maybe where the star was on the Figma prototype)? A link icon appears to the right when the user hovers over a question rectangle then they click the link icon? Then the link disappears or moves when user hovers over a different question? Feels like there's some room for potential confusion so we probably should discuss at the next office hours.

**Comment by plexish** [comment]
I mean here:
![image](https://user-images.githubusercontent.com/1039691/182975502-d2581f5e-9b8d-4f91-882b-47d730084428.png)
yep, let's discuss next time :)

**Comment by ccstan99** [comment]
My 2 concerns with that location are: (1) it feels far from the questions, somewhat inaccessible so maybe not as clear of an association and (2) expectation/interaction for when the link icon should appear/disappear may be somewhat complicated. I'm presuming the link isn't always there, correct? Does it appear on hover within the blue question bar? Does it disappear when you leave? If so, it may disappear before you click on it and the logic of keeping it on the screen might get convoluted.

I'm leaning towards having it on the blue question bar, to the right of the question. See "What is superintelligence?" below. The link icon appears when the cursor is in the bar but disappears when the cursor is no longer within the question bar. Clicking anywhere in the question bar still expands/collapse the answer. The link icon is only "active" when you hover over the icon itself. Thoughts?

<img width="792" alt="Screen Shot 2022-08-09 at 5 32 39 PM" src="https://user-images.githubusercontent.com/38997995/183784967-55e3a533-dea4-4aeb-a45b-4e52f311ebb4.png">

**Comment by plexish** [comment]
As discussed in office hours, seems reasonable.

**Comment by plexish** [comment]
Hey neat, this is done :)
