### ISSUE TITLE
SEO Preview for aisafety.info is the same as the one for stampy.ai

### ISSUE THREAD

**Issue by maxeonyx** [StampyAI/stampy-ui#220]
Eg. when a messaging app displays a preview of the site, it says Stampy and includes the old stampy pic. This harms the purpose of presenting the more professional look of aisafety.info

Eg.
![image](https://user-images.githubusercontent.com/5790555/234458664-924e8b2d-01b7-40e1-8bef-7c283bf90f60.png)

(Also please let me know if my summary isn't accurate :smile:  )

**Comment by plexish** [comment]
Yes, this should be adjusted. Anyone want to pick this up?

**Comment by Aprillion** [comment]
@ccstan99 I haven't found the new logo in https://github.com/StampyAI/StampyAIAssets, can you please upload it there?

**Comment by ccstan99** [comment]
https://github.com/StampyAI/StampyAIAssets/commit/0e6ea2711681a84ad6706ab2eecbbf340a531e17
