### ISSUE TITLE
"date approved" column in Answers API

### ISSUE THREAD

**Issue by matthewrwatkins** [StampyAI/stampy-ui#226]
It would be helpful to introduce a new column on the Answers API page (Admin panel) which gives "date approved" (the date the question/answer went live on site, or blank if it's not currently live on site). Note that some questions that are live on site get moved back to "In progress" if there are problems with them, so we want to be sure that the original date they went live gets replaced with a blank in such an instance.

**Comment by mruwnik** [comment]
@tayler6000 this should probably be moved back to the the main stampy project. I'm guessing the bot would have to do it? Or maybe it could be done in Coda as a formula?
