### ISSUE TITLE
Make tags dropdown (Answers API page) searchable or at least alphabetised.

### ISSUE THREAD

**Issue by matthewrwatkins** [StampyAI/stampy-ui#227]
The dropdown in the "tags" column of the Answers API Coda page (Admin panel) would be more helpful if it were searchable (the number of tags is now so large, that it's quite a tricky process to find all the relevant ones). At the very least, they could be listed alphabetically.

**Comment by mruwnik** [comment]
@matthewrwatkins it already is, but it's not obvious:
<img width="656" alt="image" src="https://github.com/StampyAI/stampy-ui/assets/3942390/c5efb4cc-52b1-493b-ab2b-66b5dd98a708">
