### ISSUE TITLE
Search not showing answers with keywords - stale cache

### ISSUE THREAD

**Issue by markovial** [StampyAI/stampy-ui#228]
The answers show up when I type in the full phrase but not when I search keywords.

E.g. [What is a subagent](https://aisafety.info?state=8QZH_) will not show up when I search just the word "subagent" , and [What is deceptive alignment](https://aisafety.info?state=8EL6_) doesnt show up when I search "deceptive"

Keyword search is supposed to be working when the user searches just 1 or 2 words as per [this closed issue](https://github.com/StampyAI/stampy-ui/issues/215#issue-1679068718)

**Comment by markovial** [comment]
@mruwnik

**Comment by Aprillion** [comment]
@markovial as a workaround, I cleared the cache by sending `DELETE https://aisafety.info/questions/cache` request manually and now `What is a subagent?` appears in the search results:
![image](https://user-images.githubusercontent.com/1087670/236763220-6ca4fec5-cd3b-4260-a0ee-e48bae38c041.png)

But I have to investigate why the cache did not refresh automatically, let me repurpose this issue for that.

**Comment by Aprillion** [comment]
Also, we have so much data in the cache that downloading the whole CloudFlare KV store in `https://aisafety.info/questions/cache` route no longer works => let's remove that feature and only show the Delete button on the page without downloading all the stuff, so other people will be able to delete the cache from that page without sending a DELETE request via API.

**Comment by Aprillion** [comment]
@markovial - cache updating should be more reliable now, and if you experience similar problems you can debug caching issues on https://aisafety.info/questions/cache - on the line with `allQuestions` key, if you click `Show value`, there you can check the timestamp of last update (time in UTC, don't forget to convert to local time when comparing with your clock) or you can even copy&paste the whole line to a text editor (tripple click to select whole line in most browsers) where you can search for a question title to check what UI thinks is the Coda status of that question.
<img width="471" alt="Screenshot 2023-06-05 at 12 46 35" src="https://github.com/StampyAI/stampy-ui/assets/1087670/975e5195-b20b-4e0e-ab4e-a7cb51b43111">

**Comment by Aprillion** [comment]
Hopefully no more caching issues in #246 ... but let's keep that one open to track unexpected results if there are other issues 😓
