### ISSUE TITLE
Feature Request: Ability to rehide text after [See more...] is clicked

### ISSUE THREAD

**Issue by markovial** [StampyAI/stampy-ui#238]
Currently in answers the see more just disappears after clicking. It would be nice if this was more like a toggle so that the reader can go back to what is considered the "core information" which appears before the tag.

Basically, if I click see more... and what shows up is too much information that I don't care about, I should be able to delineate between what the original author of the answer considered to be core info, and what was just extra see more info that I can hide again, if that makes sense...

[Here](https://aisafety.info?state=8HIA_) is an example of a random answer we a see more tag for easy reference of how it currently works.

**Comment by plexish** [comment]
Is this needed given that you can collapse the whole answer anyway? The old wiki-based version had this, but it never felt super useful to me, and the hide link felt kinda cluttery. Open to more opinions or reasoning though.

**Comment by tayler6000** [comment]
I think it's pretty standard UI that where there is a `see more`, there is a `see less`.  I'm also willing to get the opinions of others though.

**Comment by plexish** [comment]
@ccstan99 do you have a quick take on this?

**Comment by ccstan99** [comment]
Yes, if there's `see more`, there should be `see less`. It's both or none. Having just one without the other is indeed odd. 

Ideally, from a big picture point of view, it'd be better to cull out long answers so we shouldn't we need this at all. If it isn't "super useful", let's remove it entirely.

**Comment by markovial** [comment]
I mean there are a bunch of things that I would not consider "super useful" when trying to just get the intuition of a topic across, but are still "useful" enough to distill.

The entire point of the see more tag in my mind was that if the reader has become interested in the thing enough, there is more that they could read about it which does not involve them having to go to an overly technical research paper or blog post.

**Comment by plexish** [comment]
Okay, we can have both then.

My guess is it's pretty useful to have the option for extra detail in some case though?
