### ISSUE TITLE
Make related questions which are already on the page relocate to collapsed in the sliding in place

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#25]

**Comment by mruwnik** [comment]
This should probably also handle the case where opening a related question doesn't reshuffle them, leaving the list looking like any later related questions are part of the opened question, i.e.:
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/3942390/225761077-13901f38-46a7-42fd-94a8-53dbd2627358.png">

Changes to:
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/3942390/225761164-17675f18-2f48-4d74-b91a-87195971a191.png">

**Comment by LeMurphant** [comment]
No longer relevant with new UI
