### ISSUE TITLE
Feature Request: Dev Mode/Editor Mode Page

### ISSUE THREAD

**Issue by markovial** [StampyAI/stampy-ui#250]
It would be useful to be able to have an alternative page where the search in addition to the regular live on site results, also returned the WIP non live on site answers.

This is useful because then the editors would be able to check if the semantic similarity search engine returns appropriate results for not live on site articles before adding them to the alternative phrasings section to prevent bloat.

**Comment by ccstan99** [comment]
I've updated https://nlp.stampy.ai/ so it'll return WIP non live on site answers as well. If you still want the feature integrated into the main UI, you can leave this issue open. Otherwise, if having an alternate search option is sufficient for your purposes, you can close this issue.
