### ISSUE TITLE
Feature Request: LMGTFY Functionality

### ISSUE THREAD

**Issue by robertskmiles** [StampyAI/stampy-ui#254]
It would be cool if you could send someone a link that would pre-populate the search bar with a string. I imagine this could be done with a URL variable? Like: `https://aisafety.info/?query="How can I help?"`

**Comment by robertskmiles** [comment]
For creating links, I'm not sure. Maybe a mousover link icon next to the search bar? I don't mind if it's a hidden feature, I just want to use this myself :)

As for how it looks, I'm imagining it just runs the search as normal and shows the drop-down as though the user had just typed in the search term. I'm not sure we need to make any new UI for this feature. If no question IDs are in the link, populate with the initial questions, otherwise we can load in the questions from the URL, with the search from the URL as well.

**Comment by mruwnik** [comment]
how about something like `https://aisafety.info/question/H`https://aisafety.info/question/Howow%20can%20I%20help%32` (those aren't proper encodings, I'm just lazy) which redirects to `https://aisafety.info/?state=1234_`?
