### ISSUE TITLE
small visual bug

### ISSUE THREAD

**Issue by sakgoyal** [StampyAI/stampy-ui#255]
Small visual bug where I see a faint diagonal line across each question. Not sure why this would happen but it goes away if you click on the question, and comes back when you collapse the question. 
I'm on a 1440p monitor using brave. the problem does not happen in firefox for me
![image](https://github.com/StampyAI/stampy-ui/assets/19929553/3f1908c7-ecde-48de-909c-63d7b215c6ef)

**Comment by Aprillion** [comment]
No idea how to reproduce myself but even if reproduced, not sure how to fix ... probably some obscure CSS optimization in some versions of Chromium 🤷  let's keep open until someone will have some insight how to fix this (or if it stops happening "on its own" in case it was a Chromium bug and not our fault after all).

**Comment by Aprillion** [comment]
Dark mode looks like this now, so even if the faint diagonal line would still happen for someone, it should be less visible now 🤷 

<img width="1066" alt="Screenshot 2023-11-17 at 10 27 14" src="https://github.com/StampyAI/stampy-ui/assets/1087670/a115443f-f2c9-4bab-b90d-4ed1a974b0cd">
