### ISSUE TITLE
Iframe from airtable links

### ISSUE THREAD

**Issue by Aprillion** [StampyAI/stampy-ui#267]
See https://support.airtable.com/docs/embedding-airtable-views to convert airtable links from GDoc into iframes on the site.

Related code:
https://github.com/StampyAI/stampy-ui/blob/e65e87fe8a96da8b6dc84e08f1e98127d8b5c645/app/server-utils/url-to-iframe.ts#L5-L7

**Comment by mruwnik** [comment]
how would this be parsed? Like how the aisafety.world is handled, so it's only replaced when you have a bare link (e.g. like [http://aisafety.world/](http://aisafety.world/), but not [ai safety world](http://aisafety.world/))
