### ISSUE TITLE
Error loading answers from Brave browser on iPhone

### ISSUE THREAD

**Issue by jrhender** [StampyAI/stampy-ui#268]
I've noticed an issue with loading question on Brave browser on my iPhone.

I've observed the issue with Brave browser on mobile.
Setups that I've observed don't have the issue:
- Brave browser on MacOs
- Chrome browser on iPhone
- Safari browser on iPhone

### Repro steps
1. Using Brave browser version 1.51.2 (23.6.5.22) on iPhone
2. Navigate to https://aisafety.info
3. Click on any of the default questions or any questions from a search

### Expected behaviour
- The question answers should display

### Observed behaviour
An error message of "Error loading <the question>" is shown

<img src="https://github.com/StampyAI/stampy-ui/assets/4407464/e83ceb90-20be-4ca0-94f8-6230aff8f3b4" width="300" >

**Comment by Aprillion** [comment]
Thanks for reporting, but I'm afraid I won't be able to reproduce as I don't have an iPhone. Does it happen even after deleting browser cookies/cache? If it's possible to open browser console / network tab on Brave on iPhone, please let us know if you find more details about error message details...

**Comment by markovial** [comment]
Similar issues were observed in the regular desktop browser version about a month ago. So here is a link to a potentially related closed issue : https://github.com/StampyAI/stampy-ui/issues/257

**Comment by jrhender** [comment]
Tested today. Unable to reproduce: questions load as expected. Brave browser version is now 1.52 (13.7.3.17).
I will close this issue at fixed.
