### ISSUE TITLE
Feature Request: Hierarchical Tags

### ISSUE THREAD

**Issue by markovial** [StampyAI/stampy-ui#270]
We have like 200+ tags. Which will probably keep increasing for a while. If the point of tags is to help navigate the giant maze of questions then as they currently stand they need some improvement. So one proposal to improve is to have tag hierarchies as inspired by the [Anki hierarchical tags addon](https://github.com/pneff/anki-hierarchical-tags). Below is a visual.

I don't really like the colors in the image, but besides that basically what I imagine is like a collapsible hierarchy of tags, each of which has their own associated questions. E.g. Reward::Reward Misspecification , Reward::Reward Hacking, ... so both reward misspecification and reward hacking would be sub-tags of the reward tag, and we can use all three to categorize questions.

@plexish already did something like this for coda, but it would be nice to have this as a feature on the [tags](https://aisafety.info/tags) page too.
 
![image](https://github.com/StampyAI/stampy-ui/assets/52564817/4e6cd20a-025b-4c13-94cf-f6ff83004dc4)

**Comment by Aprillion** [comment]
The proposal sounds useful, but I don't see any hierarchical structure in https://coda.io/d/AI-Safety-Info_dfau7sl2hmG/Tags_su-dP#Tags_tuRkz/r206 yet, so not sure what it would mean for UI implementation => marking the issue for discussion.
