### ISSUE TITLE
Inconsistent related questions upon collapsing articles

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#286]
I found this issue hard to describe, I hope the [video](https://github.com/StampyAI/stampy-ui/files/12152270/collapsing_issue.zip) helps.

Say we are reading article A, and we click on related article B. This loads B and B's related questions but does not visually separate them from A's related questions. Collapsing B does not remove B's related questions so it is hard to know which one were associated to A or B.

I think the desired behavior should be to remove A's related questions upon click on B, and to remove B's related questions upon B being collapsed. In other words, only the related questions of the most recently opened article would be visible. Upon collapse, the question above it (which is still visible) would have it's related questions shown.

I am open to discussion on the end result, there might be something interesting that can be done with indenting. @plexish was mentioning infinite indenting as an option.

**Comment by Aprillion** [comment]
see also #25 ... and I remember some discussions about it half a year ago, don't remember conclusions (probably not good conclusions if not recorded in that issue) - maybe @plexish or @ccstan99 remember what were the UX complications, why we didn't improve related questions yet

**Comment by plexish** [comment]
I think we'll probably re-assess this in the UX overhaul, maybe with infinite indenting and collapsing as the expected outcome? Letting readers manually control which relateds are open seems better than hiding one set automatically when the next opens?

**Comment by LeMurphant** [comment]
Since the frontend is changing, this will be a no-op.
