### ISSUE TITLE
Gdocs suggestions showing up on site

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#287]
https://aisafety.info/?state=87AG_3119r6988r5611r
![Notice the typos](https://github.com/StampyAI/stampy-ui/assets/16197732/d1d555bd-f434-45ca-a330-7f845f75b44d)

https://docs.google.com/document/d/1tJ_XMOCdUCX387mZaNNvJhP7EquG3ZVmxRUBlh7swWA/edit
![On Gdocs](https://github.com/StampyAI/stampy-ui/assets/16197732/fa5a7ed1-4292-424b-a606-b8a8efc9d5fe)

It looks like the parser is picking up suggestions. This does not seem to happen often, I could not find other examples.

**Comment by srkaas** [comment]
It seems to happen on text with hyperlinks. See e.g. the fourth paragraph here:

https://docs.google.com/document/d/10g6U9SL0CBy__wCBTib7_WhB3S3aaFt7Fx1vVgCzg2I/edit
https://aisafety.info?state=0_

**Comment by LeMurphant** [comment]
Nemo says it's fixed, reopen if it's not
https://discord.com/channels/677546901339504640/1088468403406258196/1247514031456124978
