### ISSUE TITLE
Make text window narrower to ~80 chars/line

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-ui#302]
LessWrong people suggested making text window narrower for easier reading on desktop. Our current width is 1900 px ~120 characters/line. General wisdom is ~80 characters/line. I did some quick calculations and think we can (1) drop width to 1600px (2) increase left & right padding by 50px (3) increase text size a bit. This might need a bit of trial & error. And double-check that things don't get messed up on mobile.

**Comment by Aprillion** [comment]
Current width is similar to Wikipedia, but I guess we can make it more similar to LessWrong if that's what the target audience expects:
<img width="1800" alt="Screenshot 2023-08-09 at 17 39 53" src="https://github.com/StampyAI/stampy-ui/assets/1087670/bddbfdc9-54b5-40d2-b923-72c1a9d06434">

Note that some question titles might wrap to 3 lines on desktop if people targeted up to 2 lines on current content width 🤔

**Comment by Aprillion** [comment]
When / if this is implemented, please only apply to the light and dark themes, not to 3rd theme for embedding from #322, since the parent sites want to control max-width themselves.
