### ISSUE TITLE
Add alternative phrasings to basic search

### ISSUE THREAD

**Issue by mruwnik** [StampyAI/stampy-ui#321]
From discussion in https://discord.com/channels/677546901339504640/1125883308979535922/1154377481575485540 :

> Are alternate phrasings supposed to show up on the 1-2 word keyword search or only on semantic search?
> ...
> If it's an easy fix it might be worth including both

**Comment by ccstan99** [comment]
This issue should only apply to keyword search. Both semantic search through in-browser TF and API already support alternate phrasings.
