### ISSUE TITLE
Broken markdown parser (double question footer)

### ISSUE THREAD

**Issue by Aprillion** [StampyAI/stampy-ui#323]
Server side rendering does not match client with a console error `Warning: Prop `dangerouslySetInnerHTML` did not match.` with double-rendered question footer with tags and action buttons:
![image](https://github.com/StampyAI/stampy-ui/assets/1087670/c0cd9184-9892-46c8-9f3d-cb1e27a9c507)

Repro steps:
* open <https://aisafety.info/?state=9OGZ_>

Looks like we have invalid HTML from markdown rendering with unclosed `<div>` and unstarted `</p>`:
<img src="https://github.com/StampyAI/stampy-ui/assets/1087670/1b341543-e0d8-4091-9419-6d548c7220c6" width="300">

**Comment by Aprillion** [comment]
Got broken in https://github.com/StampyAI/stampy-ui/pull/317/commits/56e321fdc9b373aed0eeddab8141dcda513317c8

**Comment by Aprillion** [comment]
Markdown in Coda looks fine https://coda.io/d/_dfau7sl2hmG#Answers_tuile/r900&view=modal => probably something to do with insertion of `see-more`...

**Comment by mruwnik** [comment]
@Aprillion is this fixed?

**Comment by Aprillion** [comment]
I hope so 🤞  I swear that GH decides to not auto-close an issue just when I get used to it and stop checking 😭
