### ISSUE TITLE
Linking videos with specific timestamp

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#328]
I embedded a video with a specific timestamp. The timestamp does not apply to the video imbedded on the live site, it could be nice to use this when pointing to a specific point of an 1h+ video
https://aisafety.info/?state=1001_9B85r6410r6411r6412r7602r8NYDr6196r8E40r
https://docs.google.com/document/d/1sQUSq0uCGRLr-DQHLmXSAfCECPFQxObr_LGBfeSigNE/edit
https://discord.com/channels/677546901339504640/1106436191521353758/1143771645253795931

**Comment by Aprillion** [comment]
@mruwnik could you please check if this has something to do with gdocs parser?

**Comment by mruwnik** [comment]
should be better now. The parser was ignoring timestamps

**Comment by LeMurphant** [comment]
Confirmed functional on site, thanks for the super fast fix :pray:
