### ISSUE TITLE
No distinction between one newline and two newlines

### ISSUE THREAD

**Issue by leillustrations** [StampyAI/stampy-ui#349]
![image](https://github.com/StampyAI/stampy-ui/assets/48779042/613da393-52ee-4451-9bbb-f63ff55ba531)
![image](https://github.com/StampyAI/stampy-ui/assets/48779042/cdd5c9fe-d7d4-4622-9967-0f609672f854)

UI displays a fixed distance whenever there is a new line, regardless of if there is a blank line. I think it's useful in some cases for the layout to reflect whether or not there is a blank line.

**Comment by mruwnik** [comment]
should that result in an extra line or with the current line being removed?

**Comment by leillustrations** [comment]
I think the current line should be removed, but I don't feel strongly
