### ISSUE TITLE
Landing

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#362]
**Updates (12 Feb)**
- The three major links are working
- Visuals are still inconsistent with design
  - New button component (that Melissa made) is not being used (probably because it's not been pushed yet lol)
  - Imagery is cut off on top and bottom and huge gap shows to left on wide screens (imagery width and height based on viewport width is probably best)
- Could someone else check to make sure the acceptance criteria related to Coda work?

**Acceptance criteria**

* When user clicks "Start here" button, they will be led to "Introduction to AI Safety" section **done**
* When user clicks "Browse all arguments" they will be led to the corresponding section, probably titled something like "Common arguments" (exact copy pending) **done**
* When user clicks "Learn how" button they will be led to the corresponding section, probably titled something like "Get involved with AI Safety" **done**
* When clicks on cards in "Advanced content" section, they will be led to the corresponding section.
  * Coda will include input fields for the title, subtitle, and icon
  * the ordering in coda will also be reflected in the implementation
  * the top 6 in the order in Coda will be shown on this section in the landing page
  * If user forgets to add an icon or something to one in the top 6, just display it anyway, but hopefully users won't forget this

**Links**
- Landing: https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=1156%3A13124&mode=dev&t=44VVzPxsJswVwE8I-1

**Comment by melissasamworth** [comment]
@Aprillion This is done although it's still hard to see the links given they aren't semi-bold like they in the design, also the body text in the design is much larger!

**Comment by melissasamworth** [comment]
The visuals are still inconsistent with the design

**Comment by melissasamworth** [comment]
@buddy-web3 I'm seeing the same issues as before. 

Could this be related to my browser, the cache, not having pulled everything?

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/ad13aa1d-cecf-49b1-b1ef-8ec0041a5906)

**Comment by melissasamworth** [comment]
Update: Buddy will address issue from Nemo (after finding out what he meant), then merge

**Comment by melissasamworth** [comment]
Update: Padding issue

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/2641a4d0-d725-4124-b0ce-146d9ae45a2a)

Can we also make images bg images on divs that are based on viewport width? Right now there is a giant ocean of space on large screens lol.

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/47464f9b-edb7-4a44-a8f9-532d74c67427)

Also can we make the images to to the very edges? There are little gaps


![Image](https://github.com/StampyAI/stampy-ui/assets/825910/2c16bf30-d604-4f79-b90b-0ddd88081a0b)

Oh and I also need to adjust the padding on the h1

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/3bda2667-e6bd-4c33-a88d-3dee9d0e0ebd)

**Comment by buddy-web3** [comment]
@melissasamworth "Can we also make images bg images on divs that are based on viewport width? Right now there is a giant ocean of space on large screens lol. "  -- can you please look into this one? I'm not exactly sure how you want it

**Comment by melissasamworth** [comment]
Update: margins on images fixed, needs to be merged

**Comment by melissasamworth** [comment]
@buddy-web3 did you merge this? Still seeing the gaps


![Image](https://github.com/StampyAI/stampy-ui/assets/825910/f8516100-1e5b-4b2a-b94a-5d2cff730fe7)

**Comment by melissasamworth** [comment]
Okay is good, I just want to adjust the images to be based on viewport width so I'm moving it back to in progress
