### ISSUE TITLE
error page

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#365]
**Acceptance criteria**

- Main title, preferably very short
- Subtitle, preferably somewhat short

**Link**
https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=2068%3A8672&mode=dev&t=5zH2EaswPLkKJBPS-1

**Comment by melissasamworth** [comment]
@mruwnik am I looking at the right thing?


![Image](https://github.com/StampyAI/stampy-ui/assets/825910/a378dd6f-bf8b-4e1b-b6bb-6c11ae7588f0)

**Comment by mruwnik** [comment]
yup

**Comment by melissasamworth** [comment]
Hm looks fine except can we make it centered? That would mean removing the classes that were specifically for article pages.

**Comment by melissasamworth** [comment]
It still looks off center. Also it's not loading. Am I looking at the right thing?

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/723bf51f-7db1-45cc-aa33-5e2d7f7194ac)

**Comment by melissasamworth** [comment]
Update: Title is missing for Melissa (brave browser)

**Comment by melissasamworth** [comment]
Padding Nemo! 

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/36e2b54d-2bba-4f96-ae8f-4878b629fa42)
