### ISSUE TITLE
Glossary word popover

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#366]
**Update (12 Feb)**
- The popover is there, but it isn't styled like the new design yet

**Acceptance criteria**

- The first instance of a glossary term in an article will show the grey underline
- Hover over that word reveals a popover, which includes
  - Glossary term
  - Definition (make a note to writers to cap the definition at N number of character; not sure what this would be honestly since different characters have different widths)
  - Link to article page (sometimes exists sometimes doesn't)
  - Image (optional)
    - Min size of 202px width and 304px height (at the least just put a note to uploaders to make sure image is at least this size, perhaps in Coda)
    - If image is larger than this, crop it either vertically centered or horizontally centered

**Link**
https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=2073%3A8816&mode=dev&t=5zH2EaswPLkKJBPS-1

**Comment by melissasamworth** [comment]
@mruwnik 

Can you make it so the word is not repeated twice? 

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/d27a54ed-a635-44a9-840a-24d7383ef7a5)

In cases like "agentic" can you just make the word "agent" show?

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/ec14611e-1a1e-4e2d-b4e4-a7ea9d826754)

I also want it to appear under the word rather than to the right, and some styling fixes but I think I can probably fix all that.

**Comment by mruwnik** [comment]
That's mainly a copy issue, see the [glossary doc](https://docs.google.com/document/d/1Rm7tN5zTErZq0E4qqAZoNVzClS94Kb_rQOLaViu2p6c/edit).
Each glossary item has a main phrase and aliases, all of which will be underlined. Do you always want the main phrase to be the bold word, even if a different word is underlined in the main text?

**Comment by melissasamworth** [comment]
Update:
- Editors will upload exact right photo size
- Re: copy length, added ellipses if it gets too long
   - Ask editors to keep things at a certain length too

**Comment by melissasamworth** [comment]
Melissa get in touch with copy

**Comment by melissasamworth** [comment]
Update: Use term instead of alias

**Comment by melissasamworth** [comment]
Update: the term looks right, just checking to make sure the ellipsis will appear

Then just a few small styling things


![Image](https://github.com/StampyAI/stampy-ui/assets/825910/4536de46-836c-417a-af14-bfee14033b7f)

(sorry)

**Comment by melissasamworth** [comment]
Why is the line height off? Did you use the class .paragraph-small? (sorry, line height is one thing I'm a bit of a perfectionist about)

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/313c936c-e780-4431-8580-3fbb3b660985)

**Comment by melissasamworth** [comment]
also seems more text appears after the ellipsis

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/4371c1d5-d60b-4761-83af-dab4b8849c84)

**Comment by melissasamworth** [comment]
update: Melissa fix line height

**Comment by melissasamworth** [comment]
update: last issue is just that there is a bug on brave where there is more text after the ellipsis
