### ISSUE TITLE
bottom bits on standard article page

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#368]
**Acceptance criteria**

- Updated [first three letters of month name] [yyyy]
  - Based on any change made to the google doc (even fixing a typo), but not comment suggestions
- "Did this page help you?"
  - Click anywhere on left half to say "yes"
    - "No" then turns grey, and "Thanks for your feedback!" text appears immediately to the left (and stays)
  - Click anywhere on right half to say "no"
    - "Yes" then turns grey
    - Popover appears. After user clicks submit (or just clicks out, if they don't want to leave an answer), it closes, and "Thanks for your feedback" appears to left
- Clicking tags will lead to page for that tag

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/65ea1eae-5ebc-49f8-8f87-00b7631c8650)

**Links**
- Article
https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=1156%3A12840&mode=dev&t=1aLfVu2DEKlsbEf4-1
- Submit feedback popover - article page
https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=2789%3A16740&mode=dev&t=zTwTmuq08p9ZfsM1-1

**Comment by melissasamworth** [comment]
@buddy-web3 can you adjust the padding to match the design? :) E.g. the tags are right up against the line above them and should have more room

**Comment by melissasamworth** [comment]
@buddy-web3 I've updated the links to the design you're actually supposed to implement. For MVP I say forget about the "Thanks for your feedback" part

**Comment by buddy-web3** [comment]
@melissasamworth  please review the branch: https://github.com/StampyAI/stampy-ui/pull/412

**Comment by melissasamworth** [comment]
@buddy-web3 just confirming that my review was seen and adjusted, then I'll close this!

**Comment by buddy-web3** [comment]
@melissasamworth code adjusted as per review. except the last 2 comments, aren't those already as requested?
