### ISSUE TITLE
"None of these: Request an answer to my exact question above"

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#37]
Add to questions table in coda

**Comment by Aprillion** [comment]
#114 is a temporary solution with a link to wiki, @plexish wanted to have anonymous access to request new question from UI for the full solution of this issue.

**Comment by plexish** [comment]
Or via github secrets allowing the UI to log into the wiki directly to add the question, that seems fine too if we want to touch less code.

**Comment by plexish** [comment]
Re-use Stampy account from bot, probably use github secrets.

**Comment by plexish** [comment]
@mruwnik did this in #135
