### ISSUE TITLE
Stampy chatbot - copy link to clipboard and feedback tools

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#378]
**Acceptance criteria**

- If user clicks thumbs down, load popover
    - The thumbs up icon turns grey
    - In popover, user clicks one of three buttons to select
    - User must at least select one of three before "Submit feedback" button is not greyed out, i.e. before submitting
    - User can also add a comment of any reasonable length
    - After submitting, popover just disappears
    - User can also click out of popover to make it disappear
- If user clicks thumbs up, thumbs down icon turns grey
- I would say just don't let user change their answer once they have given it
- If user clicks clipboard
  - copy the link to the corresponding article page (if there are more than one, just choose whichever)
  - show "Link to response copied" to right of icons for five seconds

**Links**
https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=2197%3A6785&mode=dev&t=VPY066NyE4xc5llO-1

**Comment by zarSou9** [comment]
Note to self: Just remove button pointer when the feedback buttons deactivate
