### ISSUE TITLE
categories page

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#379]
**Update (12 Feb)**
Almost done, just a few small styling issues (see comment below)

### Acceptance Criteria
- [ ] styling should match figma
- [x] navigating to `/tags` should navigate to default tag. This is important for backwards compatibility because https://aisafety.info/tags works on current site.
- [x] URLs should be `tag/{tag id}/{tag name}`
  - Navigating to `tag/{tag id}/anything` should navigate to correct tag using id, but will try to append name where possible

**Comment by jrhender** [comment]
@melissasamworth @mruwnik for the article page, issue #382 asks that the links be "aisafety.com/id/current-title-of-article". Would it make sense to also have the category URLs have the name and the id? In the current implementation, the category URLs are `/tags/{tag name}`. Would it instead make sense to do `/tags/{tag id}/{tag name}`, similar to the articles?

**Comment by jrhender** [comment]
This tasks probably isn't quite done from a styling standpoint as the sidebar doesn't quite match figma:
- It isn't aligned under the "AISafety.info" logo
- The green highlight on the selected category isn't correct

![Image](https://github.com/StampyAI/stampy-ui/assets/4407464/9827a40c-c8d2-4760-b758-758d0fc7084a)

**Comment by melissasamworth** [comment]
Hey @jrhender quick process note: do you think it's best to talk about individual tickets here on Github? I think it probably does, and if so I'll make sure to check this daily (sorry for the lag this time).

The purpose of the IDs with articles is to make it backwards compatible, particularly for links people have shared that are floating out there. I'm not sure how many tag links people have shared. Still, backwards compatibility would be nice. Does your solution solve that problem?

**Comment by jrhender** [comment]
> The search input current says "Search articles" but it should say "Filter by keyword"

PR here: https://github.com/StampyAI/stampy-ui/pull/391

**Comment by jrhender** [comment]
> Lastly, not sure if it should belong to this issue but the widths of the layout is off. Ideally they should be the following viewport widths

@melissasamworth @buddy-web3 

Do you think the change to fix this would be in `newRoot.css`? https://github.com/StampyAI/stampy-ui/blob/04b76d21a98c0470814a78260a896f8f1e359f59/app/newRoot.css#L408

**Comment by melissasamworth** [comment]
Storybook version pushed
Still needs to be integrated with article page (Nemo)

**Comment by jrhender** [comment]
Hey @melissasamworth , could you elaborate on this point please:
> Storybook version pushed

The storybook version of one of the components was published? By "published" do you mean push to the `stampy-redesign` branch?

**Comment by melissasamworth** [comment]
> > Lastly, not sure if it should belong to this issue but the widths of the layout is off. Ideally they should be the following viewport widths
> 
> [@melissasamworth](https://github.com/melissasamworth) [@buddy-web3](https://github.com/buddy-web3)
> 
> Do you think the change to fix this would be in `newRoot.css`?
> 
> [stampy-ui/app/newRoot.css](https://github.com/StampyAI/stampy-ui/blob/04b76d21a98c0470814a78260a896f8f1e359f59/app/newRoot.css#L408)
> 
> Line 408 in [04b76d2](/StampyAI/stampy-ui/commit/04b76d21a98c0470814a78260a896f8f1e359f59)
> 
>  .group-elements {

Not sure but i can take a look soon

**Comment by melissasamworth** [comment]
> Hey [@melissasamworth](https://github.com/melissasamworth) , could you elaborate on this point please:
> 
> > Storybook version pushed
> 
> The storybook version of one of the components was published? By "published" do you mean push to the `stampy-redesign` branch?

@joy-void-joy Hey I'm sorry, I think I meant to comment this on another issue. 

Only thing remaining is "If no article title takes up 2 lines, can you still make them 100% width?" thanks :)

**Comment by melissasamworth** [comment]
@jrhender I was referring to the widths, but don't worry, Nemo took care of it

**Comment by jrhender** [comment]
Awesome, thanks for taking this across the finish line @mruwnik and @melissasamworth !
