### ISSUE TITLE
Skip steps in github actions if encodings don't change

### ISSUE THREAD

**Issue by Aprillion** [StampyAI/stampy-ui#41]
We managed to skip git commit and push steps in https://github.com/StampyAI/stampy-ui/runs/7155620125 by using `exit(1)` in previous step, but failing that step still fails the whole action.

The log message that encodings didn't change is more visible than trying to figure out why commit failed due to no files being staged, but it would be even better if the whole action was successful / just a warning and not failed.

**Comment by ccstan99** [comment]
OK, that's what I did originally but noticed it was still failing even when exit(1). Also, this action is only run manually. Should I have it scheduled to run periodically/daily? Or just manually deploy when we know there's been changes in wiki answers? We'll get error emails if there's been no change and the action fail.

**Comment by Aprillion** [comment]
After we fix the skipping so it won't fail, let's schedule it daily (or another trigger if we discuss on office hours).

**Comment by Aprillion** [comment]
fixed by #63, https://github.com/StampyAI/stampy-ui/runs/7269313504 looks good:

![image](https://user-images.githubusercontent.com/1087670/178137237-7fd678f0-b1ac-4b0e-9c44-be65479bc301.png)
