### ISSUE TITLE
mobile - categories pages

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#419]
**Acceptance criteria**
Desktop
- new page to display all categories
  - this is where the user lands when they click "browse all categories" from articles dropdown
  - categories are listed alphabetically (it doesn't really matter if that is horizontally or vertically, given there are now 4 columns)
  - filter by keyword would narrow the list based on matched strings
    - I don't really care how this happens, I would imagine the words would all just stack up in the first column 

Mobile
- same categories page exists on mobile too, obviously
- same functionality
- the individual categories page doesn't have any sidebar or equivalent for mobile

**Links**
mobile: https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=3009%3A7778&mode=dev&t=SNAwBbvUbwhNOBsL-1
desktop: https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=3054%3A9018&mode=dev&t=y9KwiAh0zgKQrTO8-1

**Comment by melissasamworth** [comment]
Update @buddy-web3 : If you want actually, we can use this same design for desktop so that when user taps "Browse all categories" they land on a desktop categories page (lmk if this is easier)

**Comment by melissasamworth** [comment]
update: Melissa create design for new page

**Comment by melissasamworth** [comment]
@buddy-web3 @mruwnik I updated this to include description and links that include desktop categories page now

**Comment by melissasamworth** [comment]
@buddy-web3 here's my QA for this

**Comment by buddy-web3** [comment]
@melissasamworth  PR: https://github.com/StampyAI/stampy-ui/pull/474

**Comment by melissasamworth** [comment]
update: PR ending
