### ISSUE TITLE
Deployment to ui.stampy.ai

### ISSUE THREAD

**Issue by Aprillion** [StampyAI/stampy-ui#42]
Add github action for deployment to cloudflare worker - see README for instructions to update wrangler.toml with following public keys before running `npm run deploy`:
* account: 841738ad455064a5846675cc41124c85
* KV: 3efee496497048eca81d3f1b036d2631

..see e.g. https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler

Contact @Aprillion to generate the `CF_API_TOKEN` from @plexish's CF account.

**Comment by ccstan99** [comment]
I tried to use the wrangler-action workflow from Cloudflare but got an error:
✘ [ERROR]The entry-point file at "build/index.js" was not found.
<img width="820" alt="Screen Shot 2022-07-10 at 6 56 04 PM" src="https://user-images.githubusercontent.com/38997995/178204706-cefd8c82-28dc-4483-ac2d-39d740828916.png">

So, I just used our regular `npm install` then `npm run deploy`

Instead of hardcoding those values above, I used GitHub's repos secret keys: CLOUDFLARE_API_TOKEN, CLOUDFLARE_ACCT_ID, STAMPY_KV_ID

**Comment by Aprillion** [comment]
Cool! Did you set up the github secrets with plex already? If not, I can have a look later after work.

**Comment by ccstan99** [comment]
We can use the same action/workflow and add a trigger on PR merge/close. So we might as well generate the encodings at the same time. It takes less than a minute and ensures everything is always up-to-date.

Right now the triggers are manual (workflow_dispatch) and schedule. I didn't put it the PR trigger to avoid throwing in too much all at once. It looks the deploy manual deploy worked.
https://github.com/StampyAI/stampy-ui/runs/7286918471

I'll try to test out the PR merge/close from my repo later. So we should wait until that's working before closing out this issue.

**Comment by Aprillion** [comment]
Merge of PR #71 seems to triggered the action from merging a PR successfully - https://github.com/StampyAI/stampy-ui/pull/71/checks

But it failed because we introduced a rule against pushing code directly to master => I will relax the rule for now and let's see next PR.

**Comment by ccstan99** [comment]
Do you remember that there was originally a force push parameter in the GitHub Action? I think it was to get around the current error we're seeing in the log, based on https://github.com/stefanzweifel/git-auto-commit-action/issues/71. Looks like you can "Restrict who can push to matching branches" while also "Allow force pushes for all users with push access."

![87848938-6ecdb200-c8ed-11ea-8e15-12ea7ff771be](https://user-images.githubusercontent.com/38997995/178898150-92883f0a-56a1-4256-a7ac-680d830e404d.png)

**Comment by Aprillion** [comment]
Ah, that force push makes more sense to me now 😅  I enabled it and updated the action to use it, but it looks like https://github.com/StampyAI/stampy-ui/runs/7334562917 still failed in the push step :(

**Comment by ccstan99** [comment]
Bummers! Any ideas how a personal access token works? That's supposed to be another workaround based on https://github.com/stefanzweifel/git-auto-commit-action/issues/71#issuecomment-660470689

**Comment by Aprillion** [comment]
Deploy after PR merges works good enough since https://github.com/StampyAI/stampy-ui/pull/74, so closing this issue and we can figure out triggers for automatic updates of encodings later.

e.g. https://github.com/StampyAI/stampy-ui/pull/84/checks
