### ISSUE TITLE
mobile - make sure every single tag that contains type has the correct class

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#420]
**Acceptance criteria:**

- Every single H tag should have no classes assigned other than color classes or padding classes
- Each tag should match the tag specified in the design
- All p tags should be assigned a class (the class specified in the design)
![Image](https://github.com/StampyAI/stampy-ui/assets/825910/572b6c32-0d67-46cf-86ba-2b7c0b2ef4cd)
- The class specified in the design matches to one of these classes in root.css this should be easy
![Image](https://github.com/StampyAI/stampy-ui/assets/825910/94691373-92c9-4501-9d8a-2b958c7a29be)
- Make sure no extra classes are assigned to p tags other than color classes or padding classes
- Make sure no typography styling is **ever defined anywhere else in the CSS**

This is all important for conversion to mobile, as well as just consistency and making our process faster!

**Comment by jrhender** [comment]
From a quick search through the code for all `<h`, I think all of the `h` tags have no classes assigned other than colour classes or padding classes now. @melissasamworth , is it okay if an `h` tag doesn't have colour and/or padding classes?

**Comment by jrhender** [comment]
@melissasamworth I think the only `p` tag that doesn't have the figma classes is this tag in `questions.add`: https://github.com/StampyAI/stampy-ui/blob/stampy-redesign/app/routes/questions.add.tsx#L86
Is this route to add a question in the new design yet?

**Comment by melissasamworth** [comment]
@jrhender yes an H without classes is fine

In the case that the type is the default paragraph type it won't have a class so this is probably okay. I think we're good if that was the last thing you found.
