### ISSUE TITLE
Mobile - make sure variables are used any time margins or padding are defined

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#423]
**Acceptance criteria**

- e.g. Margin-top: 16px; does not exist anymore, anywhere!
  - margin-top: var(--spacing-16)
- if this task is marked done, but I find margins or padding defined without variables, you will be in trouble
- I don't think this will apply for heights (actually we should specifically probably not use variables for heights) but let's wait and see how things look

This is important so that things aren't too spaced apart on mobile

**Comment by melissasamworth** [comment]
There are some whole pixel values used in this area. Not sure if "calc" should also use vars.

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/1861eac1-571f-44f5-a487-9f64b45fead6)

**Comment by mruwnik** [comment]
those have been deleted
