### ISSUE TITLE
Mobile - global nav

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#424]
**Acceptance criteria**
- Before tapping menu button
  - Logo, which leads back to home page (same as desktop)
  - Menu button on left
    - The icon is 24px by 24px by ideally the click target would be 40px by 40px but without making the padding or alignment off
- When user taps menu button on right, full screen overlay appears
  - X button takes place of menu button
  - If user taps X button they return to previous screen
  - If user taps "Articles" (make click target the entire rectangle, not just the text), load the articles dropdown mobile page
    - This functions the same as the desktop articles dropdown (somehow would be nice to reference the same component?)
    - If the user taps back arrow, go to previous screen (original menu screen)
    - If the user taps X, go back to the original screen before they tapped the menu button

**Links**
https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=2807%3A20106&mode=dev&t=zTwTmuq08p9ZfsM1-1

**Comment by melissasamworth** [comment]
Update: mostly done, the articles dropdown part is still left

**Comment by melissasamworth** [comment]
Update: Buddy needs to fix something, then he'll merge this (replace current header with new header when on mobile)

**Comment by melissasamworth** [comment]
@buddy-web3 QA linked here

https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=3076%3A9158&mode=dev&t=2noQmv2mn8MJRgSu-1

**Comment by buddy-web3** [comment]
@melissasamworth please review/approve PR: https://github.com/StampyAI/stampy-ui/pull/501

**Comment by melissasamworth** [comment]
update: PR pending
