### ISSUE TITLE
Fix Article in Storybook

### ISSUE THREAD

**Issue by jrhender** [StampyAI/stampy-ui#452]
Article in Storybook is not rendering and displaying the following error:
```
useSubmit must be used within a data router.  See https://reactrouter.com/routers/picking-a-router.
```

![Image](https://github.com/StampyAI/stampy-ui/assets/4407464/41f5e907-f14c-4ecc-bb35-0903c18d460e)

**Comment by jrhender** [comment]
WIP fix is here: https://github.com/jrhender/stampy-ui/tree/jrhender-452-fix-article-in-storybook

Fix approach is https://blog.sentiero.digital/how-to-run-remix-link-component-in-storybook

**Comment by melissasamworth** [comment]
Just going through all tasks in to-do, wondering @jrhender what's the status of this? :)
