### ISSUE TITLE
categories page desktop version

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#459]
**Acceptance criteria**
Desktop

new page to display all categories
this is where the user lands when they click "browse all categories" from articles dropdown
categories are listed alphabetically (it doesn't really matter if that is horizontally or vertically, given there are now 4 columns)
filter by keyword would narrow the list based on matched strings
I don't really care how this happens, I would imagine the words would all just stack up in the first column
Mobile

same categories page exists on mobile too, obviously
same functionality
the individual categories page doesn't have any sidebar or equivalent for mobile

Links
https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=3054%3A9018&mode=dev&t=y9KwiAh0zgKQrTO8-1

**Comment by melissasamworth** [comment]
@buddy-web3 QA https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=3087%3A9177&mode=dev

**Comment by melissasamworth** [comment]
update: PR pending

**Comment by melissasamworth** [comment]
update: melissa accept PR

**Comment by melissasamworth** [comment]
@buddy-web3 I'm still seeing 4 columns instead of 3. See the QA I linked last week: https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=3087%3A9177&mode=dev

**Comment by buddy-web3** [comment]
@melissasamworth PR: https://github.com/StampyAI/stampy-ui/pull/556
