### ISSUE TITLE
Crashes on iPhone

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-ui#46]
Tried both Chrome & Safari
Stack trace
`O@http://ui.stampy.ai/build/_shared/chunk-TVKKQU54.js:9:14040ir@http://ui.stampy.ai/build/_shared/chunk-TVKKQU54.js:12:270Zi@http://ui.stampy.ai/build/entry.client-WXWJSFRI.js:5:64683ta@http://ui.stampy.ai/build/entry.client-WXWJSFRI.js:9:111849bs@http://ui.stampy.ai/build/entry.client-WXWJSFRI.js:9:104095Kf@http://ui.stampy.ai/build/entry.client-WXWJSFRI.js:9:104026st@http://ui.stampy.ai/build/entry.client-WXWJSFRI.js:9:103886yi@http://ui.stampy.ai/build/entry.client-WXWJSFRI.js:7:100770Ve@http://ui.stampy.ai/build/entry.client-WXWJSFRI.js:7:98330Ur@http://ui.stampy.ai/build/entry.client-WXWJSFRI.js:9:118922@http://ui.stampy.ai/build/entry.client-WXWJSFRI.js:9:120580Zs@http://ui.stampy.ai/build/entry.client-WXWJSFRI.js:7:101248qr@http://ui.stampy.ai/build/entry.client-WXWJSFRI.js:9:120566module code@http://ui.stampy.ai/build/entry.client-WXWJSFRI.js:9:123964evaluate@[native code]moduleEvaluation@[native code]@[native code]promiseReactionJob@[native code]`
![IMG_3995](https://user-images.githubusercontent.com/38997995/177011152-3e27bdc3-3c87-45ae-bf8e-5df38efc85b8.PNG)
![IMG_3997](https://user-images.githubusercontent.com/38997995/177011153-d2f51f8e-1424-4674-896e-415f74e8e938.PNG)

**Comment by Aprillion** [comment]
all browser engines on iPhone are Safari, they just pretend to support Chrome/Firefox/anything else ¯\\\_(ツ)_/¯

**Comment by ccstan99** [comment]
Oh boy, I did not know that. Thanks for your quick response... even with your gate just announced!
