### ISSUE TITLE
add copy to bottom section (copy)

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#460]
**Acceptance criteria**

- Each card should have a title, a subtitle, and an image
- Keep char count for type to something close to what is shown in design
- Soon I will have new images (maybe the person who owns this task can show me where to put them)

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/9b88ed73-834c-4064-acea-f18ce0c0f17b)

**Comment by LeMurphant** [comment]
Melissa says size is 72x72. I will put placeholders, eventually they will be replaced.

**Comment by LeMurphant** [comment]
@melissasamworth when you want to update the images, you can do so under the "icon" table in this page. Just copy-paste from your file browser
https://coda.io/d/AI-Safety-Info_dfau7sl2hmG/All-Answers_sudPS

**Comment by melissasamworth** [comment]
Cool

**Comment by LeMurphant** [comment]
@melissasamworth The titles and subtitles are up. I made some of the subtitles questions, what do you think?

The images have been uploaded but are not working for unknown reasons. Do you want me to remove them?
