### ISSUE TITLE
Nav: "sections" is missing x2

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#469]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/dbdeb4be-2f24-4331-9781-fd48d6abae26)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/0074aaa3-8bb3-4aea-b5e3-8002cf63fc9f)

**Comment by LeMurphant** [comment]
The ones one site are the good ones, the Figma had placeholders.

The order still has issues, but opened https://github.com/StampyAI/stampy-ui/issues/507

**Comment by ricewithabee** [comment]
@LeMurphant this issue was about the word "sections" being missing, but nemo has fixed it already 👍🏼

**Comment by LeMurphant** [comment]
Makes sense, thought it was about the missing sections themselves. I will reopen this just so it can follow the flow.

**Comment by LeMurphant** [comment]
Fixed
