### ISSUE TITLE
/home: hero button text should be bold

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#471]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/1fa9bf54-abf4-48e4-9992-82bc42a896d8)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/cdad2d77-43b1-4320-8c92-75ad27d1926c)

**Comment by melissasamworth** [comment]
Yes @mruwnik this button is actually not the secondary class but the primary-alt class. 

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/2c1886bf-3732-4278-8608-0616639a797f)
