### ISSUE TITLE
/home: cards missing icons and body text

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#477]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/d0282047-504d-47b7-8890-437b0b8e4067)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/57105ac7-fdab-46cb-8067-0a5002887201)

**Comment by mruwnik** [comment]
this is a copy issue
