### ISSUE TITLE
/articles: body text too large

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#480]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/aee0f1d4-d656-4de8-a12a-422cf59024f2)

I personally find myself zooming out to 75% to make it comfortable.

**Comment by ricewithabee** [comment]
@melissasamworth

**Comment by melissasamworth** [comment]
@ricewithabee yeah I've gotten about 3 people saying it's too big, and 1 says they like how big it is. I'll make it smaller but I'm going to batch this together with my next round of design changes. For now keep it as is.

**Comment by ricewithabee** [comment]
FWIW another person gave feedback on this saying it's too big
