### ISSUE TITLE
/articles: line spacing too large

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#481]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/2a211df6-eae5-48cd-ad3f-db058d5534dd)

I think it should be reduced by about 10%.

**Comment by ricewithabee** [comment]
@melissasamworth

**Comment by melissasamworth** [comment]
I like the line spacing! Let's take this as a data point but I want a few more data points until I'm ready to make the change. So close it for now but mentally noted :)
