### ISSUE TITLE
/articles: reading time and copy/edit buttons too big

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#482]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/9d7f18a4-2ef4-403c-9e7a-9b0d4b3b3c4d)

They're a bit too in your face.

**Comment by ricewithabee** [comment]
@melissasamworth

**Comment by melissasamworth** [comment]
Ah okay I'll take this as feedback and change the design when I can, don't implement the changes yet.

The buttons are actually wider than in my design so getting the padding right on those is enough to close out this task


![Image](https://github.com/StampyAI/stampy-ui/assets/825910/f6e35796-6e5b-4990-a46c-34ea700043c0)
