### ISSUE TITLE
/articles: some links go to a Stampy Google Doc instead of a published article

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#483]
Example from https://redesign.aprillion.workers.dev/questions/8AEQ/What-is-behavioral-cloning:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/2d18697d-8320-43df-935b-88144da1d792)

Not sure whether this is intentional or not.

**Comment by mruwnik** [comment]
Sort of. The problem is that only live on site articles should be viewable on the page - articles that are still being written are sort of in a grey zone where they exist, but aren't on the site. So this is a compromise. They should get automatically updated when the status of an article changes
