### ISSUE TITLE
/"What are OpenAI Codex and GitHub Copilot?": glossary item underlining bug

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#490]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/c41d9566-345a-4391-85d5-c80a5bfd32aa)

https://redesign.aprillion.workers.dev/questions/6628/What-are-OpenAI-Codex-and-GitHub-Copilot

**Comment by mruwnik** [comment]
what's this issue with this?

**Comment by LeMurphant** [comment]
The words "Language Model" seem to be doubly underlined. If I were to guess, the issue is that both "Large language models" and "language models" are in the glossary, we want the longest hit only to be underlined
