### ISSUE TITLE
/articles: long load times

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#492]
For me (Chrome on Mac) the time it takes to load an article (while showing the screen below) averages 5–6 seconds.

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/f0c47c26-0168-4af9-9e68-4697653a79f8)

**Comment by mruwnik** [comment]
yup, this is because the first time it's called it has to call coda. Subsequent queries should go faster. It can also be an issue with the cloudflare worker being slow, as it's a free one
