### ISSUE TITLE
/articles: location of footnote popover

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#495]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/3cf9965d-8f5f-401f-b869-5fc09bc73721)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/f205ed4c-d9eb-461b-a6ed-e89ee13d1a75)

**Comment by melissasamworth** [comment]
Yeah I'm actually fine with this how it is @ricewithabee feel free to remove this one
