### ISSUE TITLE
/articles: footnote "return to text" button reopens the article in a new tab instead of scrolling back to text

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#496]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/426bdab9-8f8a-4ff7-a154-b2d1b5f4998a)

Example: https://redesign.aprillion.workers.dev/questions/6222/Isn%E2%80%99t-it-immoral-to-control-and-impose-our-values-on-AI

**Comment by melissasamworth** [comment]
@mruwnik doesn't seem done on the redesign site e.g. https://redesign.aprillion.workers.dev/questions/6194/Is-AI-safety-about-systems-becoming-malevolent-or-conscious

**Comment by mruwnik** [comment]
it works for me on firefox and sort of on brave, i.e. brave seems to have slight problems with the back links, but if I click a second time it scrolls back to the reference link

**Comment by bryceerobertson** [comment]
Works fine for me (on Chrome) now. All good on your end @melissasamworth?

**Comment by bryceerobertson** [comment]
Ok never mind, this one doesn't work for me https://aisafety.info/questions/9J1L/Alignment-research
