### ISSUE TITLE
redo section titles (copy)

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#502]
**Acceptance criteria**

Each section title should be about ~15 characters (avg)
Don't use questions
Input into Coda

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/0d6de3f2-ffdf-48b1-96cc-628a99fa3be8)

**Comment by LeMurphant** [comment]
What are the main categories of technical alignment research? -> Categories of technical alignment
What models and predictions have been made about the future of advanced AI? -> Predicting future AI
Want to help with AI safety? Get involved! -> Get involved with AI safety
Not convinced? Explore the arguments. -> Explore the arguments
New to AI safety? Start here. -> Intro to AI safety
What is AI governance? -> AI governance

These changes are live. Tell me if you think some are inappropriate

**Comment by LeMurphant** [comment]
@melissasamworth I notice that we have a few subsections in the "Intro to AI safety" section that are questions
https://docs.google.com/document/d/19NfeKa6flGzoZnubQMoqHte4ZXoQ7w5yBABpLINNRtk/edit
I suggest rephrasing these to remove the questions, e.g.
"What's this is about?" -> "What this is about"
Are you OK with that?

**Comment by melissasamworth** [comment]
Categories of technical alignment --> "Technical alignment categories"? 

Just a note that I find "Explore the arguments" ambiguous

Re: questions. I was going to agree and then realized I actually don't mind a couple of them being questions as long as they're short. I'll let you decide ultimately though.

**Comment by LeMurphant** [comment]
Another round of updates, see more context here
https://discord.com/channels/677546901339504640/1088468403406258196/1215180100073562142

Get involved with AI safety -> What can I do?
Categories of technical alignment --> Alignment research

I looked at all the questions in subsections and they looked good to me, so I'd keep them for now.

@melissasamworth regarding "explore the arguments", considering that this section mostly addresses misconceptions, how would you name it?
