### ISSUE TITLE
finalize IA (copy)

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#504]
**Acceptance criteria**

Each section has sub-sections assigned and ordered
Each sub-section has all it's articles assigned and ordered
All is reflected in Coda. Make sure that the website itself parallels this too by looking through the website.

**Comment by LeMurphant** [comment]
The last two advanced section (Technical alignment + AI governance) still need to be done (I expect them to be done tomorrow), the rest should be good

**Comment by LeMurphant** [comment]
It is done, please notify me if there are issues.

**Comment by melissasamworth** [comment]
Awesome thanks!

**Comment by melissasamworth** [comment]
@ricewithabee can do QA on copy, pretty much just making sure all the acceptance criteria is met, and what shows on the site reflects coda?

**Comment by LeMurphant** [comment]
@ricewithabee you can find it here
https://coda.io/d/AI-Safety-Info_dfau7sl2hmG/Categorize-answers_suzym
I found that the easiest way was to select the introductory or advanced tags, or else to select a parent. Coda will order them with the "order" column, which also reflects what the site should be
