### ISSUE TITLE
hero copy

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#505]
**Acceptance criteria**

50 to 100 char

Process notes:
1. Do research quickly on what makes good hero copy
2. Put together strategy (brainstorm) what strategy directions
3. Put together a list of possible hero copy options

Schedule a call with Rob, CC, Plex, Melissa and whoever else in copy. I imagine that call will  be a combo of 2 and 3 but coming with some options couldn't hurt.

**Comment by LeMurphant** [comment]
Steven will do it. Waiting for @mruwnik to add him to GH to assign it to him.

**Comment by melissasamworth** [comment]
Cool I'll leave it to you to reassign, thanks!

**Comment by LeMurphant** [comment]
The choice is done, the task is set in https://github.com/StampyAI/stampy-ui/issues/562
