### ISSUE TITLE
/articles: format tooltips

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#509]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/287380f4-36a7-48f6-91ad-d68dd623cfad)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/5e9c2abe-01dc-4c5e-a6b7-09cb2f7b00b1)

Both buttons at the top and the one at the bottom.

**Comment by ricewithabee** [comment]
Padding is good on the "Copy link" button but it has the wrong font and the "Edit article" buttons (x2) have too much padding.

**Comment by bryceerobertson** [comment]
The tooltips for the top buttons have disappeared altogether now. The bottom ones look good except for a z-index problem with one:



![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/33432cb6-9a58-459e-bcdc-e73d60a2a9d6)
