### ISSUE TITLE
Footer copy: left paragraph

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#510]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/80d51387-bfe8-4a4b-88a2-2f45edf0398e)

I suggest this slight change (flows better):
We’re a global team of specialists supported by volunteers from various backgrounds concerned about the possibility of human extinction from future AI.

**Comment by ricewithabee** [comment]
@LeMurphant @srkaas this alright with you?

**Comment by LeMurphant** [comment]
There had been a lot of discussion on this, but this is what we settled on. Open to be changed if stakeholders disagree.
