### ISSUE TITLE
/articles: paragraph spacing too large

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#512]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/98a1f835-e1e7-46c0-9cb4-d5c91339e03d)

Compare with spacing here:
- https://support.apple.com/en-nz/guide/mac-help/mchlecadabe0/14.0/mac/14.0
- https://www.aisafetybook.com/textbook/4-7

**Comment by ricewithabee** [comment]
@melissasamworth

**Comment by melissasamworth** [comment]
I like the gaps and did it on purpose this way. I'll take this as a data point as well, but want more data before making the change, so close for now.
