### ISSUE TITLE
/articles: "See more..." button seems unnecessary

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#514]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/9055e6a0-bcb9-4409-a7ab-ff25c365ffbb)

Example: https://redesign.aprillion.workers.dev/questions/8QH5/Would-a-slowdown-in-AI-capabilities-development-decrease-existential-risk

None of the articles are particularly long (this example is 6 minutes). I think the button makes the page unnecessarily messy, and also leads to some confusion about the reading time (whether it's 6 minutes for the whole article or just until the button).

**Comment by ricewithabee** [comment]
@melissasamworth

**Comment by melissasamworth** [comment]
Hmm yeah, it is not the best design. I remember a few stakeholders wanting to keep it but... I probably agree with you. Let's remove it for now.

**Comment by mruwnik** [comment]
This is mainly a copy thing

**Comment by LeMurphant** [comment]
@melissasamworth I remember us discussing this recently, what was the final verdict on whether we are removing this functionality? We (in copy) are OK either way, since it's not as relevant as when the website was infinite scrolling and it's not a lot of work to remove it from all existing articles.

If we decide to remove them, we can do so in the articles and style guide and then @mruwnik can eventually remove the code that deals with it from the backend

**Comment by LeMurphant** [comment]
After discussing this with the folks from Copy, @melissasamworth and @ricewithabee we could benefit from a discussion to better understand the pros and cons of removing the [See more...] functionality

**Comment by ricewithabee** [comment]
My opinion:
Reasons to keep it: none.
Reasons to remove it: cleaner UI, less confusion around the reading time stated at the top of the page.

**Comment by LeMurphant** [comment]
Some positive user feedback on this functionality
https://docs.google.com/document/d/1SY2VqnSfd4qCMnv9rRyDiThJsIKIDOiTARbKYLHwKng/edit

[Intro to AI safety](https://aisafety.info/questions/9OGZ/)
I stop him at “See more” and ask him about it. He thinks the 4-minute helps. He thought the “see more” might make him lose the page, and was happy to see that it does not. He thinks the “see more” has some value to feel like you can get a quick version. Would have expected the label “see more” to point to other articles, and not to the rest of the article. Suggest we might want to say “keep reading” or something. I point out that “keep reading” is already used, but we will take it into consideration.

**Comment by LeMurphant** [comment]
I opened a PR to completely remove the feature from the codebase
https://github.com/StampyAI/stampy-ui/pull/833
