### ISSUE TITLE
/articles: Stampy chatbot missing from bottom of page

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#516]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/d17d6080-4342-4d72-90c8-a682d51f6e7f)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/bfacf86b-9c94-471b-83a0-a85c5b0e14fa)

Presumably intentional but just in case it isn't.

**Comment by melissasamworth** [comment]
I had originally done this so that the "try asking" questions at the bottom might be relevant to the article. We don't have that yet, and I also have sort of changed my mind and feel that no one is going to scroll this far. fine with leaving it out at least for a while.
