### ISSUE TITLE
/home: make clicking Send (or a pre-written question) cause Stampy to already start answering

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#517]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/58743c3d-a753-4726-8a66-3693f753a0f4)

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/b0bc1306-903f-44e0-a23a-7764263bc7a3)

Not sure whether this is possible/easy, but it would avoid the user having to click Send twice: once on the .info homepage and then again on the chatbot page. Or in the case of the pre-written questions, clicking the question then clicking send.

**Comment by melissasamworth** [comment]
Yeah we had wanted to but just a tech challenge here. I'd say close this and we'll address it later.
