### ISSUE TITLE
Footer: copyright notice

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#522]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/3100fe05-4f36-42c0-98a1-4bf87070e619)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/60eab3a2-5cce-4b4f-8864-61f07d087d86)

**Comment by melissasamworth** [comment]
we can keep the copy notice how it is on the site, feel free to close this one!
