### ISSUE TITLE
/articles: article fails to load when linked to from /categories

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#524]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/0d352268-d7e1-430a-80d7-5722f7e32968)

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/3521ee0a-c3c8-4bf9-9997-be4a1096e603)

Sometimes just the title loads.

**Comment by jrhender** [comment]
Discussion on stampy dev call on 2024-03-7:
- The behaviour seems to be on first load of an article (so the article hasn't yet been cached by the worker), the "Loading..." behaviour occurs
- Our best guess is that there is a race condition between the result being returned and a timeout where the frontend "gives up"on receiving the data
- Hope is that a larger cloudflare worker on the production deployment will reduce the frequency of this issue. If it doesn't priority to fix may be higher.
