### ISSUE TITLE
/articles: missing "Keep reading!" section from last article in each section

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#525]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/144cdc77-5970-43a8-a205-eaa88f699bdf)

Missing section:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/177a50a4-a5bd-4183-9142-6ff7c2b72739)

Example: https://redesign.aprillion.workers.dev/questions/A3MU/Wouldn't-AIs-need-to-have-a-power-seeking-drive-to-pose-a-serious-risk

Note that for these articles, "Continue with the next entry in XYZ" should be "Start with the first entry in XYZ". The button should also be "Start→" instead of "Next→".

**Comment by melissasamworth** [comment]
I am not sure enough about this to make a decision yet, so let's leave it how it is. Technically we did want at least the "jump to a related question" part of the bottom section though

**Comment by LeMurphant** [comment]
In some cases, it's normal that there are no related articles, but this is not the case here. I found other weird cases, I see no thread linking them.
