### ISSUE TITLE
/home mobile: "Not convinced?" section should have 3 articles instead of 2

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#526]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/92ba62e1-af94-4a48-8f58-2ee6da4e208e)

Having two makes it seem like some kind of dichotomy, like those are the only two. Having three is both aesthetically pleasing and suggests (correctly) that this is just a selection of many arguments.

**Comment by melissasamworth** [comment]
Nah I chose to put two! Close this one
