### ISSUE TITLE
Remove selected Q from search dropdown

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-ui#53]
After a user has selected a question from the search dropdown menu, it should be removed from the list so they can't try selecting it again, which currently causes the system to get stuck.
<img width="996" alt="Screen Shot 2022-07-05 at 11 24 02 AM" src="https://user-images.githubusercontent.com/38997995/177391668-6e3cba7b-5a23-4d63-8c14-3a76cb5306f3.png">

**Comment by Aprillion** [comment]
I rather fixed the bug so the system is not stuck - #56.

We don't have the `pageid` of a question in the search results, so it would a bit more complicated to filter the search results, and I also like the behaviour that clicking on a search result moves existing question to the top (e.g. if I would have 20 questions open and want to navigate to that particular one when it catches my eye in search results)...
