### ISSUE TITLE
/articles mobile: secondary nav text colour + chevron cut off

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#531]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/5ea4a281-87e5-484f-b3c0-2817be9cf68d)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/94ea0b7e-3283-45d1-9c4c-807365da6064)

**Comment by jrhender** [comment]
Reproduced again on aisafety.info at dd1e10e and locally at [8b67900](https://github.com/StampyAI/stampy-ui/pull/574/commits/8b67900bf992f07fd80fa12fc14e9f6c79743444) using chrome and safari on iPhone.
Perhaps this is a webkit mobile browser issue again.

**Comment by jrhender** [comment]
Seems like the style is coming the "user agent stylesheet", so my thinking is that this button just needs a colour class.

![Image](https://github.com/StampyAI/stampy-ui/assets/4407464/ba4e6517-19a9-4265-bad9-30963c61afd1)
