### ISSUE TITLE
/articles mobile: arrows left of section and subsections shouldn't be there

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#532]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/67d33593-2c84-49f3-83b0-487aa6a3d9cc)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/4783ca61-ae5f-44a5-8829-aabc5eec18a6)

**Comment by jrhender** [comment]
This seems fixed to me from my test of on `stampy-redesign` branch at commit 2a5551b and on [redesign.aprillion.workers.dev](https://redesign.aprillion.workers.dev/questions/9OGZ/Intro-to-AI-safety)

Could you retest when you have a moment @ricewithabee ?

![image](https://github.com/StampyAI/stampy-ui/assets/4407464/0d85f12b-7629-4def-84a6-aeb3c407c6e7)

**Comment by jrhender** [comment]
Ah yes, I do see it on Chrome mobile browser as well [image](https://github.com/StampyAI/stampy-ui/assets/4407464/3597c45a-e512-4438-9759-6394db4f9109)
