### ISSUE TITLE
Check for duplicates in related questions

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-ui#54]
"Where can I learn about AI alignment" is definitely an important and popular question, but we shouldn't need to show it multiple times on a page. In general, if a question is already on the page, we probably should remove and keep the one closest to top of screen?
<img width="997" alt="Screen Shot 2022-07-05 at 10 31 50 AM" src="https://user-images.githubusercontent.com/38997995/177392495-9989b0a6-6f20-4449-b587-8d89cd006b58.png">
<img width="995" alt="Screen Shot 2022-07-05 at 11 27 04 AM" src="https://user-images.githubusercontent.com/38997995/177392576-acb8bd4c-1a76-48b1-a6d5-762c1dab878f.png">

**Comment by Aprillion** [comment]
Wiki issue with redirects, one is page id 5635, the other 8125.

@plexish said it would be solved by the big cleanup they are doing with Matt, so let's see after that.

**Comment by plexish** [comment]
I think #25 was our plan for this, but we can patch for now by fixing the initial questions related lists.

**Comment by ccstan99** [comment]
Yes, they're very similar but I was more concerned with the initial interactions here. Overall, things already look a whole lot better today with the initial questions & their related questions cleaned up. So, I'll close this one out.

It sounds like the UI is already checking for duplicates using page id but the wiki had the same question with 2 separate page ids (5635 & 8125). I'm still able to get that question more than once on screen, so something still amiss.
