### ISSUE TITLE
images still missing in advanced section (1 of 3 launch blocking)

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#547]
![Image](https://github.com/StampyAI/stampy-ui/assets/825910/1d4e9712-fa52-42dc-a8ee-ed9808374ff8)

**Comment by mruwnik** [comment]
this is a copy issue. They're not inputted correctly in Coda

**Comment by LeMurphant** [comment]
@mruwnik my understanding is that I input them all in the same way (convert, move to coda), and the results seem unpredictable
see https://github.com/StampyAI/stampy-ui/issues/460
Do you want me to remove them for now @melissasamworth ?

**Comment by mruwnik** [comment]
Somethings wrong if it looks like this in coda:
<img width="226" alt="image" src="https://github.com/StampyAI/stampy-ui/assets/3942390/c7ce4beb-39ed-43eb-b566-ee0469c537a2">

In this case, the image is saved as a markdown link, rather than the actual link. So it's something like `![some pic](http://url.to.pic)`, as opposed to just `http://url.to.pic`. I don't know why that is, though

**Comment by LeMurphant** [comment]
@mruwnik All 4 advanced articles show that in coda, and only one of them shows up on site, I'm not sure why. I have attached a video of how I add the .png files, am I doing something incorrectly?
[move_png.zip](https://github.com/StampyAI/stampy-ui/files/14558614/move_png.zip)

**Comment by LeMurphant** [comment]
You appear to be right, ctrl-c + ctrl-v gives a different result. I will attempt to update them.

**Comment by LeMurphant** [comment]
@mruwnik I used the copy-paste method, and it shows ok in Coda for a second then reverts to the "bad icon". I refreshed the site, and one of the images appeared (governance), but not the others.

Video: 
[copy.zip](https://github.com/StampyAI/stampy-ui/files/14594339/copy.zip)

Files I am uploading: 
[advanced_images.zip](https://github.com/StampyAI/stampy-ui/files/14594354/advanced_images.zip)

@melissasamworth I set the images at size 72x72, but they seem to get compressed horizontally. I uploaded 
![governance](https://github.com/StampyAI/stampy-ui/assets/16197732/7a4ad376-6339-4ebd-91c5-3327dfcc2340)
 and the screenshot gives 
![sc](https://github.com/StampyAI/stampy-ui/assets/16197732/1ab28abc-0fa7-41e7-8ea4-35d6ab438bb9)

**Comment by LeMurphant** [comment]
Split the second half of my previous comment into https://github.com/StampyAI/stampy-ui/issues/553

**Comment by LeMurphant** [comment]
The issue was that the Coda was set as an URL and not an image, it's fixed.
