### ISSUE TITLE
Glossary terms do not update

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#551]
I updated the entry for "Large Language Model" at least 48 hours ago so that the main entry would show this instead of LLM. Even after a refresh, it seems like the website still uses "LLM" as the term in bold in the pop-over
https://redesign.aprillion.workers.dev/questions/6953/Do-people-seriously-worry-about-existential-risk-from-AI
https://docs.google.com/document/d/1Rm7tN5zTErZq0E4qqAZoNVzClS94Kb_rQOLaViu2p6c/edit
![glossary](https://github.com/StampyAI/stampy-ui/assets/16197732/502985d9-c41b-4aed-b07c-e10015d43004)

**Comment by mruwnik** [comment]
The backend job was failing - should be better now. Hopefully

**Comment by ricewithabee** [comment]
@LeMurphant you wanna confirm this?

**Comment by LeMurphant** [comment]
I'm afraid it still does not work, even after refreshing the cache.
See https://aisafety.info/questions/6628/What-are-OpenAI-Codex-and-GitHub-Copilot

**Comment by LeMurphant** [comment]
This bug is still active, was not fixed by https://github.com/StampyAI/stampy-ui/pull/578

**Comment by mruwnik** [comment]
how about now?

**Comment by LeMurphant** [comment]
The original problem with the glossary entry "LLM" is fixed. I do not know if this will become an issue with future changes, but I will close for now.
