### ISSUE TITLE
Image compression in advanced section

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#553]
See https://github.com/StampyAI/stampy-ui/issues/547#issuecomment-1995979234

Splitting to have different bugs from "inability to upload images"

Not launch-blocking

**Comment by LeMurphant** [comment]
@melissasamworth there was some discussion that we might want to have icons instead of AI generated images, what do you think?

**Comment by mruwnik** [comment]
ping @melissasamworth

**Comment by bryceerobertson** [comment]
> @melissasamworth there was some discussion that we might want to have icons instead of AI generated images, what do you think?

I'm 100% for this

**Comment by melissasamworth** [comment]
@bryceerobertson sorry, I suck at checking github notifications. 

YES. Let's please get rid of those terrible ai-gen images. I've just been lazy.
