### ISSUE TITLE
yes or no feedback widget does not work

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#558]

**Comment by melissasamworth** [comment]
@buddy-web3 here's my QA 

https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=3282%3A6274&mode=dev&t=hQcFAfHLSm7VwBOB-1

**Comment by buddy-web3** [comment]
@melissasamworth PR: https://github.com/StampyAI/stampy-ui/pull/574 
the modal goes away after 6 seconds of being out of focus. will try to make it disappear when clicked away at a later point. (current logic makes it tricky)

**Comment by melissasamworth** [comment]
There are too many issues with this one. Including the fact that now the three buttons show which were supposed to be for just the bot. I don't see enough relative value to to keep spending time on this, can we comment it out and just let the person say "yes" or "no" and that's all? @buddy-web3

**Comment by melissasamworth** [comment]
@buddy-web3 putting back to in progress. move to design review when it's been commented out

**Comment by buddy-web3** [comment]
@melissasamworth PR: https://github.com/StampyAI/stampy-ui/pull/582
