### ISSUE TITLE
Multiple titles for same article

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#561]
![mismatch](https://github.com/StampyAI/stampy-ui/assets/16197732/771ecf36-aee8-489b-81a3-8183f1c7f3b1)
![not_convinced](https://github.com/StampyAI/stampy-ui/assets/16197732/146a2b7b-da5b-45a3-9ccd-8225de23d8e5)

The title is supposed to be "Objections and responses". I was able to see the correct title at some point, but am unable to reproduce. See also https://discord.com/channels/677546901339504640/1088468403406258196/1216948933746626591

Notice the titles vs URLs. This happens even after I clear the cache.

**Comment by mruwnik** [comment]
still a cacheing problem, but deeper down :D Should be better now
