### ISSUE TITLE
Update copy based on meeting last Fri

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#562]
I would imagine this means
- Updating the copy matrix based on our feedback (e.g. "Start here" instead of "Start reading")
- Working with Nemo to get it implemented
- Use the hero copy that was voted first

**Comment by LeMurphant** [comment]
For some context and discussion, see the following thread. This GH issue is the authority when the thread conflicts with it
https://discord.com/channels/677546901339504640/1088468403406258196/1219782864896524338

See https://github.com/StampyAI/stampy-ui/issues/554 for update to one of the title cards

Hero copy final result, after the vote: 
**Your guide to AI safety**

Change "Start reading" to "Start here"

on the bot page (not currently live), change "This is an early prototype that sometimes makes things up" to "This is an early prototype that is sometimes inaccurate" 

The "About us" will also change, but this is not decided yet, I will link to it when it is. @mruwnik you're welcome to work on the others, or wait for the official text for the "About us"

**Comment by LeMurphant** [comment]
Update on "about" can be found at https://github.com/StampyAI/stampy-ui/issues/564
