### ISSUE TITLE
Update "about" in footer

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#564]
Currently is:
We’re a global team of specialists supported by volunteers from various backgrounds who are concerned about the possibility of human extinction from future AI.

New version:
We’re a global team of specialists and volunteers from various backgrounds who want to ensure that the effects of future AI are beneficial rather than catastrophic.

**Comment by ricewithabee** [comment]
"instead of" instead of "rather than" sounds smoother to me

**Comment by LeMurphant** [comment]
I still have a preference for "rather than", but can change it if others endorse "instead of"
