### ISSUE TITLE
Add a "tab title" that corresponds to the title of an article

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#566]
![title](https://github.com/StampyAI/stampy-ui/assets/16197732/7fb8e52d-32b3-46c4-96a8-653128cf4fdd)

Would make it easier to browse when you have multiple tabs open

**Comment by ricewithabee** [comment]
@mruwnik we should probably also change the default tab title to AISafety.info instead of Stampy, since users don't necessarily know what Stampy is

**Comment by LeMurphant** [comment]
Looks fixed (and pretty!), closing this
