### ISSUE TITLE
Articles that are not "live on site" still appear in the "related questions"

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#567]
See the last entry in
https://aisafety.info/questions/8EL7/How-does-%22chain-of-thought%22-prompting-work

![few-shot](https://github.com/StampyAI/stampy-ui/assets/16197732/7a5aea74-d27b-4457-a63e-452e477c9096)

Clicking on it brings us to an empty article
https://aisafety.info/questions/ACSE/What-is-few-shot-prompting

I'm ok with people being able to access the latter URL, but it should not be linked anywhere on site

**Comment by mruwnik** [comment]
(fixed on https://redesign.aprillion.workers.dev)

**Comment by LeMurphant** [comment]
Confirmed fixed on the Aprillion site
