### ISSUE TITLE
Clicking the on footnotes should not open a new page

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#572]
e.g. https://aisafety.info/questions/8486/What-is-AI-safety#fnref1-8486

Both clicking on the footnote and on the "back" arrow should keep you on the same page IMO, to avoid the confusion. Another option is to make the footnote non-clickable, as the hover might be enough.

**Comment by ricewithabee** [comment]
@LeMurphant maybe add this to #496

**Comment by LeMurphant** [comment]
Good catch. Duplicate of https://github.com/StampyAI/stampy-ui/issues/496
