### ISSUE TITLE
Clearly identify the start of footnotes

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#573]
See user feedback https://docs.google.com/document/d/1SY2VqnSfd4qCMnv9rRyDiThJsIKIDOiTARbKYLHwKng/edit

![footnote](https://github.com/StampyAI/stampy-ui/assets/16197732/942d5afe-96e6-4982-92a5-f7a6f07b7d5e)

It is not currently clear where the footnotes start. I suggest making the footnoted text smaller, having a clear header to specify them, or both

**Comment by LeMurphant** [comment]
See also https://github.com/StampyAI/stampy-ui/issues/698

**Comment by zarSou9** [comment]
@LeMurphant any thoughts?

![Image](https://github.com/StampyAI/stampy-ui/assets/148247390/fb1af87b-9a75-4cd5-9fee-d51d6c033189)

**Comment by LeMurphant** [comment]
@zarSou9 looks good to me!

**Comment by LeMurphant** [comment]
Has been implemented.
