### ISSUE TITLE
/article: "Intro to AI safety" page has a missing full stop

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#575]
It's in the Google Doc but not on the site.

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/75600c41-6fd5-41e9-91c9-93bc064ca9b6)

**Comment by LeMurphant** [comment]
The period was not there a few weeks ago, seems a synchronization issue similar to https://github.com/StampyAI/stampy-ui/issues/576

**Comment by ricewithabee** [comment]
Closing this issue as it's a sync issue described by #576
