### ISSUE TITLE
/articles: suggestions that haven't been accepted are displayed on the site

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#579]
Seems pretty high priority since currently randos can add stuff to the site by making suggestions in the Docs.

Example: https://aisafety.info/questions/6713/I%E2%80%99d-like-to-get-deeper-into-the-AI-alignment-literature.-Where-should-I-look

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/06776053-4da4-4281-8913-22e900e52314)

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/fe085384-14f5-4ea4-98c3-9a818e051ceb)

**Comment by LeMurphant** [comment]
This is a known bug that also affected the previous site. It comes from the way that we parse Google Docs and is not an easy fix, so we won't fix it for now.
