### ISSUE TITLE
Unanswered questions should fail gracefully

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#58]
<https://ui.stampy.ai/?state=7767_>

https://stampy.ai/wiki/What_does_alignment_failure_look_like%3F

**Comment by Aprillion** [comment]
https://github.com/StampyAI/stampy-ui/blob/master/app/stampy.ts#L53 is supposed to return `¯\_(ツ)_/¯` if there is not element with id `canonicalanswer`, so not sure why this happens => needs more investigation.

**Comment by plexish** [comment]
The coda system works fine, closing.
