### ISSUE TITLE
/article "How can I help?": related questions don't appear

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#580]
From Steven.

It looks like all of the "How can I help?" section articles don't have related questions at the bottom.

https://aisafety.info/questions/8TJV/How-can-I-help

**Comment by LeMurphant** [comment]
I believe this page has dedicated code that shows the sub-branches instead of related questions, which afaik no other page does. @melissasamworth or @mruwnik can confirm, but I think this will be a wontfix

**Comment by mruwnik** [comment]
yes, this is the desired behaviour
