### ISSUE TITLE
Update "edit" button text

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#581]
Previous text: Edit article
New text: Suggest changes in Google Docs

For context, see https://docs.google.com/document/d/1SY2VqnSfd4qCMnv9rRyDiThJsIKIDOiTARbKYLHwKng/edit?disco=AAABKO4G-MY

**Comment by mruwnik** [comment]
you might have to change the permissions of that file

**Comment by LeMurphant** [comment]
Just gave you access @mruwnik , in the future I will put these in Notion, which can be read by everyone.

**Comment by melissasamworth** [comment]
@mruwnik tooltips aren't showing at all anymore on the redesign branch :(


![Image](https://github.com/StampyAI/stampy-ui/assets/825910/971cfd47-3fc0-44ff-8d38-d9b3fed3508e)

**Comment by LeMurphant** [comment]
Confirmed functional on Aprillion redesign.
