### ISSUE TITLE
Chatbot: settings

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#589]
**Acceptance criteria**

Front-end
- Make sure you have gotten Melissa's lesson on CSS
- Add the settings icon fixed to the bottom left, i.e. this always shows and in this position, even when user is scrolling
- Popover and settings icon are styled like in designs (linked)

Back-end
- When user clicks the settings icon, the popover shows
- If user clicks outside of popover, it disappears (but changes in answer are recorded)
- User can choose 1 of the 3 possible answers ("Default" is highlighted by default)
- Hook up the change in choice to the backend so it's reflected in the bot

**Links**
https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=3479%3A8163&mode=design&t=dg1esxPyfTqHQMnF-1

**Comment by melissasamworth** [comment]
Look good. Only if it's easy could you make it so when user clicks outside of the box it disappears?

**Comment by melissasamworth** [comment]
![Image](https://github.com/StampyAI/stampy-ui/assets/825910/bc6e72fb-6060-47f0-9207-029413a46587)

**Comment by mruwnik** [comment]
it already does

**Comment by melissasamworth** [comment]
@mruwnik sorry to bother 😭. But it doesn't seem that changing the answers here is updating the backend. It gets a bit buggy and then goes back to default.

**Comment by melissasamworth** [comment]
Update: I think this is still an issue. Let's test it together and see

**Comment by mruwnik** [comment]
works for me. Can you reproduce this?
