### ISSUE TITLE
Unanswered question text

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#59]
Let's make the text for both unanswered and uncanonically answered questions be:

_We don't have an answer for this question yet. Would you like to [write one](link to create answer using same url as the page write answer button)?_

**Comment by plexish** [comment]
Currently it's
_(empty)_

**Comment by mruwnik** [comment]
where is this to be done? The easiest solution would be to just update the new documents template. A much more interesting option is in the [$question.tsx](https://github.com/StampyAI/stampy-ui/blob/master/app/routes/questions/%24question.tsx#L108) file.

To test this, find an unanswered question in [coda](https://coda.io/d/AI-Safety-Info_dfau7sl2hmG/Write-answers_suuwH#_luboi), an set its UI ID (you'll have to unhide that column for that table) in the url, as `http://localhost:8787/?state=<UI ID>`, e.g. `http://localhost:8787/?state=90A3`

**Comment by plexish** [comment]
just updating the answer template is a nice quick patch, I'll do that for now.

I'm not sure I follow your second suggestion?

**Comment by mruwnik** [comment]
it's just a pointer to where this would have to be done in the frontend code, if someone wanted to do this as a first issue
