### ISSUE TITLE
Chatbot: chat initiation

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#593]
**Acceptance criteria**

Other stuff (Nemo, Buddy)
- The chat with response is initiated when:
  - User clicks a button on the chat landing page (Can’t we just put the AI in a box?)
  - User types at least one character and presses enter or the plane icon
  - User clicks one of the buttons from the widget on the home page
- Opens in same tab

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/acbefff8-e58b-469c-9ed5-5c190642d0d4)

CSS (Melissa, Archana)
- 

**Links**
https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=1156%3A19240&mode=design&t=dg1esxPyfTqHQMnF-1

**Comment by melissasamworth** [comment]
Update: there are still some styling issues



![Image](https://github.com/StampyAI/stampy-ui/assets/825910/c143e2f6-9bb5-4ec5-8b1c-1f7ba340b00c)

The sticky bottom bar. The shadow on the box.


Also, what the user actually types is not what is input, but rather the question above. This is okay maybe, but if we do it this way we need to make sure the question above is what is filled in on the chatbot as what the user said.

**Comment by mruwnik** [comment]
can you explain what you mean with the input?

**Comment by melissasamworth** [comment]
Looks like it's fixed!

**Comment by melissasamworth** [comment]
I'm assigning this to Myles because I think all the remaining fixes are in a pr
