### ISSUE TITLE
Chatbot: Continue the conversation buttons

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#594]
**Acceptance criteria**

Everything except CSS (Nemo, Buddy)
- After any answer is returned, show "Continue the conversation" below it, with the buttons for 3 more questions
- 3 questions are returned
  - between 0 and 3 are based on the current algorithm of how closely they are related to the first question
  - fill in the others with a pool of randomly generated questions from our top 20 (get this top 20 from copy)
- Clicking the button has the same effect as typing that phrase character for character and then pressing return

CSS (Melissa, Archana)
- Make sure the visuals match the design

**Links**
https://www.figma.com/file/qqfeYAh6Z7QdyJXsQjIUfh/Stampy?type=design&node-id=1156%3A19268&mode=design&t=9lrQdhpZsKoF1qGs-1

**Comment by melissasamworth** [comment]
@mruwnik I believe "fill in the others with a pool of randomly generated questions from our top 20 (get this top 20 from copy)" is left to do

**Comment by buddy-web3** [comment]
@melissasamworth this one is already merged, keep clicking a “continue conversation” question and eventually you’ll see some that end in “ — from pool”

**Comment by melissasamworth** [comment]
> [@melissasamworth](https://github.com/melissasamworth) this one is already merged, keep clicking a “continue conversation” question and eventually you’ll see some that end in “ — from pool”

Okay cool. This overall looks good. I would say before closing it out we should remove the "-- from pool", would you be able to do that really quickly?

**Comment by melissasamworth** [comment]
Update: Let's get Nemo to confirm this is done.

The only issue I can see is that I want the button text to be left-aligned
