### ISSUE TITLE
Old Glossary entries not expiring properly

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#600]
https://aisafety.info/questions/7772/What-are-some-of-the-leading-AI-capabilities-organizations

![good](https://github.com/StampyAI/stampy-ui/assets/16197732/601eaa02-d990-4856-8b34-a22ca4457972)
![broken](https://github.com/StampyAI/stampy-ui/assets/16197732/649f7064-9bb2-4f5b-8bd5-ea9c60ad8eb4)

The term "AI capabilities" used to be in the glossary as an alias but we removed it. It appears like it kept the old definition and the image broke. We need to clean up such instances.

**Comment by mruwnik** [comment]
should be fixed now - give a bit till the cache expires

**Comment by LeMurphant** [comment]
Confirm fix works, there was a duplicate issue in Coda, see
https://discord.com/channels/677546901339504640/1193299418259140690/1234904126861742091
