### ISSUE TITLE
Have non-live articles show a banner when displayed

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#611]
ref https://discord.com/channels/677546901339504640/1219361047077453845/1235590654512467968

In theory, these articles should not be easily accessible, but if we make a mistake or someone goes to the URL directly, they can reach them, e.g. https://discord.com/channels/677546901339504640/1219361047077453845/1235590654512467968

While I was not able to find the old banner, but I'm quite confident that it used to tell you you were in progress on the old site

IIRC the determining factor to see if it shows on site is Coda, not the Gdocs location

**Comment by mruwnik** [comment]
it used to look like this:

![Image](https://github.com/StampyAI/stampy-ui/assets/3942390/0a9a7bc5-4881-418f-8675-e207a137ffbd)

**Comment by melissasamworth** [comment]
@LeMurphant I'm a bit confused about this task. The links go to an empty Discord for me. Can you give me links to these types of articles so I can check Nemo's implementation? Each of the 3 I guess (Still uncertain about the design choices here but nbd).

**Comment by LeMurphant** [comment]
I think we never ended up using "Controversial" and "Well established", although we might in the future. I think implementing them is low priority.
@melissasamworth  An example of an article that would fit "In progress" is this one
https://aisafety.info/questions/8W8C/
Note it should in theory not be discoverable, but it could be if we make a mistake (which is likely to happen sometimes).

**Comment by mruwnik** [comment]
it's not on master, so check this link: https://redesign.aprillion.workers.dev/questions/8W8C/
Or go to the example question: https://redesign.aprillion.workers.dev/questions/0

**Comment by mruwnik** [comment]
@melissasamworth you can change the colours and icon [here](https://coda.io/d/AI-Safety-Info_dfau7sl2hmG/Tags_su-dP) - they get fetched from coda

**Comment by mruwnik** [comment]
Where?
![image](https://github.com/StampyAI/stampy-ui/assets/3942390/24cf7d93-f98f-4b6e-8941-9170ed31fe2f)

**Comment by LeMurphant** [comment]
I like it! I'll close the issue since the feature is now present, but @melissasamworth feel free to open a new one for the shadow issue if you think it's relevant.
