### ISSUE TITLE
Settings icon issues

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#637]
1) There's an extra bit of green on the right side
2) It's a bit squeezed i.e. not perfectly circular

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/6efa1d92-9a98-4782-a542-0d83411c2efe)

**Comment by bryceerobertson** [comment]
@zarSou9 it still looks squashed to me?

**Comment by zarSou9** [comment]
Yeah.. it is, but I couldn't un-squash it in the figma. I can find another settings icon if you think its worth it

**Comment by bryceerobertson** [comment]
It does bother me a lot lol maybe this will suffice?

![settings1](https://github.com/StampyAI/stampy-ui/assets/98026499/437ddd6d-108c-4c30-ae1a-24582107dff2)

**Comment by zarSou9** [comment]
uhhhhhhhhh fiiiiiiiine, I'll fix it

**Comment by bryceerobertson** [comment]
Looks fab :)
