### ISSUE TITLE
Text too big

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#640]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/3d748213-d6a9-4c92-9453-196bbbebb9f2)

**Comment by bryceerobertson** [comment]
@zarSou9 what's the deal with this issue?

**Comment by zarSou9** [comment]
Well I mean it isn't an issue in the sense that the size matches the design. I figure we are just going by Melissa's design unless there is something obviously wrong. Sorry, I should have asked before closing

**Comment by bryceerobertson** [comment]
All good, that makes sense. We don't have a place for bot feedback yet so I've just added a note to the [general feedback database](https://www.notion.so/a17d2e4968b448c984bcc9227470444d?v=1833c2b8e923460bb19dfcbd48e3f480)
