### ISSUE TITLE
Sometimes gets stuck on "Sending query..."

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#643]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/674f176a-2c55-4a52-a636-5235549a4b30)

**Comment by melissasamworth** [comment]
Update: needs steps to reproduce @bryceerobertson

**Comment by bryceerobertson** [comment]
Prompts causing it to happen:

- "Test" > "Test again" > "Tell me about superintelligence"
- "Tell me about superintelligence" > "Are you a bot" > "Are you buggy"
- "Tell me something" > "Tell me something" > "Tell me something"

Conclusion: It happens on the third prompt, seemingly always.

**Comment by bryceerobertson** [comment]
Looks like it's happening on the 4th prompt now 

<img width="1728" alt="Screenshot 2024-06-05 at 18 15 45" src="https://github.com/StampyAI/stampy-ui/assets/98026499/fe77bde1-cd48-4279-ad54-8cbab47308b3">

**Comment by bryceerobertson** [comment]
It happens for me with these prompts:

"What is AI Safety?" > "What is an AI (2)" > "What is a robot (3)"
"Say something interesting" > "Another one" > "Is AI safe?" > "How safe is it?"
[A bunch of human-written responses, which don't seem to trigger the problem] > "How will we know" > "Is it even possible to know?"
<img width="1728" alt="Screenshot 2024-06-06 at 11 12 01" src="https://github.com/StampyAI/stampy-ui/assets/98026499/78fb9804-73ca-41e5-a474-8deb3fe3310b">


So it seems to be on the third or fourth prompt. But note that this doesn't happen with human-written responses, only bot responses.

**Comment by melissasamworth** [comment]
Yep same

**Comment by LeMurphant** [comment]
Issue cropped up with release candidate when I tested it
