### ISSUE TITLE
Citation popovers often extend far beyond viewport

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#644]
Reducing the default text size will help but it won't be enough.

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/48f46633-2cbc-4731-ae67-a7108711e407)

**Comment by melissasamworth** [comment]
Assigning to me to think about some design things

**Comment by zarSou9** [comment]
I've reduced the size to a reasonable fixed height. We can revisit this after launch if users are wanting more text in the popup

**Comment by bryceerobertson** [comment]
Is there a way of making the height and widths dynamic so that they don't go beyond the viewport at all?

**Comment by zarSou9** [comment]
Although I do want to make it so the modal goes behind the question bar, cus currently its not doing that and it looks weird imho

**Comment by bryceerobertson** [comment]
Yeah agreed, I guess that's a z index thing (I learnt about that yesterday haha)

**Comment by bryceerobertson** [comment]
Perhaps complicated to implement but one solution could be making the popover appear **above** the number if there's more space in the viewport above it, or **below** the number if there's more space below it. That combined with the fixed height you created should be enough to keep it entirely visible I think.
