### ISSUE TITLE
Thumbs up/down button design

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#646]
Seems the box is a bit too wide and hands are too small.

Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/57913b0b-f2bc-409d-af29-f003c1031a11)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/259762e5-5cca-4f8a-8f31-8823628e2436)

**Comment by melissasamworth** [comment]
Update: I think Myles' pr may fix this let's see
