### ISSUE TITLE
Landing page: missing full stop

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#648]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/825c84ef-c955-4299-9b4e-3fcaff8f5819)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/5e589124-5f82-4b3e-86e0-87114a171a2a)

**Comment by melissasamworth** [comment]
Hah so "full stop" is how kiwi's say "period"?

**Comment by bryceerobertson** [comment]
Haha you mean "period" is how Americans say "full stop"?
