### ISSUE TITLE
Refreshing page clears chat history

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#654]
Just flagging because I'm not sure whether this is by design or not. If we change the behaviour such that the chat history doesn't get cleared, then we should probably have a button for clearing it since I can imagine people wanting to start afresh.

Alternatively, if we keep the current behaviour where refreshing clears the chat history, then I think clicking AI Safety Chatbot in the nav should do the same thing.

**Comment by bryceerobertson** [comment]
@melissasamworth

**Comment by melissasamworth** [comment]
@bryceerobertson I agree that clicking it the nav should do the same thing :)
