### ISSUE TITLE
Landing page: apostrophe

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#655]
Couldn't help including a couple Bryce-nitpicks 😉

Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/cbac47e7-315d-483e-8758-e4bbf70065e1)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/148d2ddf-3ee1-4c21-bc65-dd2b086afd3d)

**Comment by melissasamworth** [comment]
I love your level of obsessiveness. Not sure this is something we can fix though, just how the browser renders the typeface vs. Figma
