### ISSUE TITLE
Videos too small

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#662]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/9ce0184f-4066-4fee-8b2f-171511a909bf)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/72e0097d-6e40-42f9-b8d1-57c03a287b8b)

**Comment by melissasamworth** [comment]
@mruwnik this is actually a site-wide problem so if we could address it all that would be ideal

**Comment by mruwnik** [comment]
fixed in parser, but it'll take a while for changes to appear

**Comment by melissasamworth** [comment]
Seems to be appearing small in some places still, hopefully we're still in the lag phase and this will get fixed



![Image](https://github.com/StampyAI/stampy-ui/assets/825910/9554be1a-c918-46fc-a022-9b7d80ce5d74)

**Comment by mruwnik** [comment]
do you recall what article this was?

**Comment by bryceerobertson** [comment]
That's "What is AI Safety?", although for me it's showing as big.

<img width="1728" alt="Screenshot 2024-06-06 at 10 56 10" src="https://github.com/StampyAI/stampy-ui/assets/98026499/9c33a863-feb3-4213-a0a3-9c9be32a8e39">
