### ISSUE TITLE
Suggested text in prompt box should change after first prompt

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#663]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/1aed8943-4269-4ab7-acd4-5939ef0d9f47)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/9699c362-e31c-4f0e-b52a-8e8544cc79eb)

**Comment by melissasamworth** [comment]
@mruwnik This was Buddy's task, I thought he had taken care of this but I suppose not. Anyway I imagine it's more backend and that you may have more context about where he left off so assigning to you.
