### ISSUE TITLE
Human-written responses: citation popover should wrap

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#666]
At the moment if it's long it touches the edge of the viewport.

Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/b307dbf5-45b3-4306-8111-5a2238926291)

**Comment by melissasamworth** [comment]
So these aren't actually citations but footnotes. I would rather just remove the hover altogether, and the brackets around the numbers, to make it more clear these are footnotes.

**Comment by mruwnik** [comment]
I very much like on hover footnotes, and actively dislike when a website doesn't have on hover footnotes, so that should be kept, as it's super useful. I'll remove the brackets, though

**Comment by melissasamworth** [comment]
Update: Myles or Melissa does CSS
