### ISSUE TITLE
Human-written responses: user has to click citation number twice

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#667]
It seems that the first click just changes the URL, then the second click scrolls to the citation in the footer.

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/6a9bb8ed-542c-4da0-8cb0-84603edba4ac)

**Comment by melissasamworth** [comment]
I actually just want to get rid of these so I would say just close this out. Unless you veto me, as you are the only witness right now and I'm not totally sure, feel free to do so. @bryceerobertson

**Comment by bryceerobertson** [comment]
Fine with me
