### ISSUE TITLE
Clicking a suggested question sometimes leads to a bot-generated response instead of a human one

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#668]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/8cdbfdf2-f33a-41a6-8b61-ca47d6a06b72)

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/b441ba59-89a5-47ec-a138-9a9b147cbf38)

**Comment by melissasamworth** [comment]
@mruwnik I'm not sure if this is a matter of backend matching, or if there are some questions available that don't have a human-written match. If it's the former, do your thing. If it's the latter perhaps bring it up with whoever has chosen those sets of questions and they fix it.

**Comment by bryceerobertson** [comment]
The question was the same, so I guess it's the former

**Comment by bryceerobertson** [comment]
<img width="1728" alt="Screenshot 2024-06-05 at 18 06 29" src="https://github.com/StampyAI/stampy-ui/assets/98026499/e9dca695-c6d1-4d9c-8500-a63a10bb5556">

**Comment by bryceerobertson** [comment]
It also happens with the third question though, which does have an article.

<img width="1728" alt="Screenshot 2024-06-06 at 10 59 52" src="https://github.com/StampyAI/stampy-ui/assets/98026499/eb008c48-e048-4cd8-baf8-82416b889de7">

**Comment by mruwnik** [comment]
https://github.com/StampyAI/stampy-ui/blob/stampy-redesign/app/components/Chatbot/index.tsx#L111 
It's on the stampy-redesign branch, which makes it harder to find

**Comment by melissasamworth** [comment]
My update: clicking on the third question now seems good the few times I tried it, i.e. human-written response appears.

Then if I type the response character for character bot-generated response appears.

So maybe this is an issue with the semantic matching. @mruwnik

**Comment by LeMurphant** [comment]
@mruwnik I suggest fetching these questions in a similar way to the ones in _poolQuestions_ in _Followups_. Actually, IMO we could use the same mechanism for both, with the starter questions polling from these 19 questions.

Furthermore, it happens semi-frequently that titles to questions change. Usually this will not happen in dramatic ways but if you could simply query the ID and dynamically get the title I think it would be preferable to hard-coding the title in the code.

**Comment by melissasamworth** [comment]
Update: We want the pre-canned questions always to match the exact title of the question (and update even when the question changes)
