### ISSUE TITLE
"Continue the conversation" appears even when there are no suggested questions

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#669]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/0fbabf3c-ad20-4b8e-95da-4f0458159497)

**Comment by melissasamworth** [comment]
The problem is instead that there there are no suggested questions. Suggested questions should always appear.

**Comment by melissasamworth** [comment]
Not sure what steps to reproduce are so will leave QA for @bryceerobertson
