### ISSUE TITLE
Button to copy chat thread missing

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#673]
Site:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/47d867ca-841a-45a6-843e-dbb406a7a256)

Figma:

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/f4e4b264-79ff-41b5-befd-b5a761df8348)

**Comment by melissasamworth** [comment]
@bryceerobertson we decided against including this. I'll remove it from the designs. When you see this just delete the ticket
