### ISSUE TITLE
Suggestion: Gradually replace AI generated images

### ISSUE THREAD

**Issue by ITR13** [StampyAI/stampy-ui#674]
Currently the site uses AI generated images in it's definition popups and "Advanced Sections" buttons, but doesn't have any page detailing if these are ethically sourced or what their training data was:
![image](https://github.com/StampyAI/stampy-ui/assets/4341642/f87748ba-10a3-453a-bdd0-b36570539854)
![image](https://github.com/StampyAI/stampy-ui/assets/4341642/6dd90161-dde1-4e08-ad60-95db3dfd5791)
![image](https://github.com/StampyAI/stampy-ui/assets/4341642/36d59311-fb81-432f-adc8-ca5b9dd15ddb)

The ethics behind generative AI is still under heavy debate, and a lot of people might view the site in a negative light if they spot AI generated images. People who are against generative AI are also likely to want safer AI, so keeping these images can be detrimental to the cause.

My suggestion is to gradually replace the AI generated images with ones contributed by artists. Preferably also doing steps to ensure it's easy to see what images still haven't been replaced, and making it easy for artists to contribute an image since not everyone knows how to use GitHub.

This of course excludes images like the ones on "[What is interpretability and what approaches are there?](https://aisafety.info/questions/8241/)" that are used as examples.

**Comment by LeMurphant** [comment]
This is an interesting perspective. My (relatively uninformed) view was that the use of these images was debated if it was either 1) Emulating the style of a specific artist or 2) Replacing the work of an existing paid artist.

Given that it seems unlikely to me that we would pay artists to produce images for e.g. the glossary, the ethical constraints do not seem to apply as much to us. Still, if the perception is "AI-generated images -> bad", then it might be worth taking into consideration and switching to a paid bank of images.

At the moment, images for the glossary and icons for the sections are produced by prompting DALL-E, which I don't expect to have the best standards in terms of fair use of artists's work. If there is a platform that generates images that are more ethically sourced, I suggest we move to it even if the quality is lower. Unfortunately, if the people visiting the site cannot see the difference, this might not help the perception.

**Comment by ITR13** [comment]
> This is an interesting perspective. My (relatively uninformed) view was that the use of these images was debated if it was either 1) Emulating the style of a specific artist or 2) Replacing the work of an existing paid artist.

There's definitely variation in how people feel about it. I think within artist circles it's a lot more frowned upon than in other places, which makes sense since they're affected by it the most. But there's definitely people who are fine with it there too, or are fine with it if it doesn't emulate/replace work like you say.

> Given that it seems unlikely to me that we would pay artists to produce images for e.g. the glossary, the ethical constraints do not seem to apply as much to us. Still, if the perception is "AI-generated images -> bad", then it might be worth taking into consideration and switching to a paid bank of images.

Obviously very difficult to tell how people will perceive it in advance, but I figure having a discussion about it is good. I personally don't think switching to a paid bank of images would be necessary. The rest of the website is open source both in content and code, so doing the same for images could work too. 

> At the moment, images for the glossary and icons for the sections are produced by prompting DALL-E, which I don't expect to have the best standards in terms of fair use of artists's work. If there is a platform that generates images that are more ethically sourced, I suggest we move to it even if the quality is lower. Unfortunately, if the people visiting the site cannot see the difference, this might not help the perception.

I'm unaware of any platforms that are more ethically sourced unfortunately. It might be smart to have a small text saying "Image generated with DALL-E" somewhere to not seem like it's being hidden? Not sure if that would change people's perception of it though.

**Comment by Algon-33** [comment]
I'm closing this because:
1) We have no sign at the moment suggesting users are not using the site because of AI images. 
2) I agree with Murphant's reasoning about this particular usage of AI art not being much of an ethics violation. 
3) This seems unlikely, but anyone bouncing off the site due to our use of AI art, I do not think they would read much of our content, as I am doubtful that the content team would argue that AI art is unethical to the degree artists claim it is. 

Now, the AI icons for the advanced section _are_ ugly. I would be very glad if ITER decides to replace it with something better. OR if we see that users prefer that we don't use any AI art, then I think we should remove it from the site.
