### ISSUE TITLE
Mobile: Misc

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#678]
**Acceptance criteria**

- Global navigation should be mobile version
- Buttons should take up full body width

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/7af7db09-b385-45a0-b77a-396a7a23f542)

- "Human-written response" should be left-aligned with text underneath

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/61d279a7-d373-4781-ae2b-93e4d9417779)

- Hide settings icon and settings for mobile

**Comment by bryceerobertson** [comment]
@zarSou9 this looks like it's done?
