### ISSUE TITLE
Mobile: reference hover

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#679]
**Acceptance criteria**
- When user taps on a reference number in a bot response, the position of the page shifts so that the number tapped is 16px from the top of the screen, and the popover is below it
- Clicking anywhere outside the popover closes it out, until then keep it open
- If the popover goes past the length the screen, make sure user can scroll and still read the whole thing
- Note that there may be an issue if the number is at the end and the popover is very long. I'm hoping with the additional questions at the bottom creating space, this doesn't happen often. So ignore this edge case for now.

**Links**
[Figma](https://www.figma.com/design/qqfeYAh6Z7QdyJXsQjIUfh/.info%3A-Redesign?m=dev&node-id=3939%3A31902&t=zdx0wcWvtNEpVpPo-1)

**Comment by melissasamworth** [comment]
@mruwnik do the HTML and components and such, and I'll do the styling

**Comment by melissasamworth** [comment]
Design updated and good to go @mruwnik

**Comment by mruwnik** [comment]
@melissasamworth you can finish the styling now
