### ISSUE TITLE
[See more...] only works after having opened and closed the question

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#68]
No example possible as the new backend does not support [See more...] at all, but likely to pop back up if we re-use that code to get it working again.

**Comment by plexish** [comment]
We're going to refactor the brief/detailed system, rendering this irrelevant.

**Comment by Aprillion** [comment]
Not related to #79, same problem will happen with `See more...` as currently with `Show detailed answer`, e.g. <https://ui.stampy.ai/?state=7757_> => reopening

**Comment by Aprillion** [comment]
@plexish feel free to reopen if still relevant, but the version implemented by @mruwnik  should work fine I hope
