### ISSUE TITLE
Mobile: prototype warning

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#681]
**Acceptance criteria**
- Desktop prototype warning is hidden on mobile
- Mobile shows this warning (text is modified) 8px below text input

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/3ab10bff-c352-4cc9-ad7c-c262c565e585)

**Comment by bryceerobertson** [comment]
@zarSou9 Looks done?
