### ISSUE TITLE
Footnote hover

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#688]
**Acceptance criteria**

- Footnote superscripts have no brackets (already done)
- They are the standard green color
- When user hovers over the number, show the footnote hover
  - Style should match design
- When user clicks the number, scroll down so that the start of the footnote is at the top of the user's screen
- For mobile, do the same as for the reference hovers in the chabot
  - The acceptance criteria for this:
When user taps on a reference number in a bot response, the position of the page shifts so that the number tapped is 16px from the top of the screen, and the popover is below it
Clicking anywhere outside the popover closes it out, until then keep it open
If the popover goes past the length the screen, make sure user can scroll and still read the whole thing
Note that there may be an issue if the number is at the end and the popover is very long. I'm hoping with the additional questions at the bottom creating space, this doesn't happen often. So ignore this edge case for now.

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/4e38f2a7-bdc0-4806-9bc6-bc9708157b08)

Note that this task was created for the bot, but ideally it addresses the entire site

**LInks**
[Figma](https://www.figma.com/design/qqfeYAh6Z7QdyJXsQjIUfh/.info%3A-Redesign?m=dev&node-id=3939%3A32057&t=HIqYMyuPucRXcgeH-1)

**Comment by bryceerobertson** [comment]
@mruwnik I think these should all be the normal green

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/d233c4c5-ca16-4af0-bde7-b60f13585250)

**Comment by bryceerobertson** [comment]
@zarSou9 the footnote numbers are still showing up as multicolored for me?

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/bc179d10-c715-40aa-bdc0-86ab8bfb8807)

**Comment by zarSou9** [comment]
I think the multicolored is good. It helps differentiate between footnotes, and it looks pretty imho

**Comment by bryceerobertson** [comment]
Fair enough, better let @melissasamworth have the final say though.

**Comment by mruwnik** [comment]
I also like the colours, for the same reasons
