### ISSUE TITLE
URL change for [See more...], so you can link directly to detailed answer

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#69]
I noticed myself wanting to do this as a reply to this bounty: https://www.facebook.com/groups/bountiedrationality/posts/3247277178849656/, with the short version of https://ui.stampy.ai/?state=6703_ being insufficient. Might be mostly a sign to only have a long answer to that particular question for now.

Maybe a + in the URL for detailed?

**Comment by Aprillion** [comment]
I don't like this, can we avoid short/long details in the first place, then we won't need this feature either?

**Comment by plexish** [comment]
hm, I have intuitions that as we get a bunch of editors we'll wish we had this split as the answers gradually get longer with valuable but non-essential information, and that some readers will want far more detail than others.. but I'm happy to put development on this on ice until we end up getting requests in that direction as my intuitions might be wrong.

Would you prefer to use just the briefest description on the UI and remove the existing toggle for now,?

**Comment by ccstan99** [comment]
I can totally understand why some editors and readers will want more details. However, from a UX perspective, it feels odd to have a very long detailed answer embedded into a list with other collapsable Q&A. Given our current setup, it'd be preferable to have long answers chunked to smaller related Q&A. For example, the bulk of the long answer to "How does AI taking things literally contribute to alignment being hard?" is already in the link to [Goodhart's law](https://stampy.ai/read/Goodhart%27s_law). BTW, will all the content in https://stampy.ai/read remain or is the new UI supposed to replace it?

Alternatively, how would you guys feel about displaying maybe the 1st 2000 (or some n, less for mobiles) characters followed by ... link to the detailed answer on its own page either in the wiki or wherever? That's a common convention for news and blog indices. We already have the precedence of people leaving the UI to follow other links within answers. This might encourage editors to be more concise (within 2000 or some n chars) but still allows us to serve answers that aren't brief enough without overwhelming the UI. 

Thoughts?

**Comment by plexish** [comment]
Agreed that we want to encourage editors to chunk things where possible.

> how would you guys feel about displaying maybe the 1st 2000 (or some n, less for mobiles) characters followed by ... link to the detailed answer on its own page either in the wiki or wherever?

oo, I like this idea. ... is more well-known as a UI than [Show detailed], for sure. Can we make it expand in the page itself though, rather than taking them to a new page? And do we want different cutoff points for mobile? This will make it harder for editors to design a good experience for all readers, though I could put a marker at both of these points in the wiki.

> We already have the precedence of people leaving the UI to follow other links within answers.
This is not final desired behavior, see #23.

That one crazy-long answer could just be marked as non-canonical as a fix, I'd rather do that than have people leaving the UI.

**Comment by Aprillion** [comment]
I can imagine automatic cutoffs (even different for mobile/desktop) to be displayed in some coloured background on the wiki (for the editors) by a JS utility... But at that point, manual short/long description has the same complexity and might be more flexible - the main benefit of an automated cutoff would be that wiki editors would see it immediately after save/preview that an answer is too long to show all of it in the UI without `[Show more]`.

**Comment by tayler6000** [comment]
If we do automatic cutoffs, it would be cool if Stampy told you how long your message was, and maybe even show you where the cutoff would be, when you tell Stampy to post an answer.

**Comment by ccstan99** [comment]
If there's an automatic cutoff, ideally, we should display a character count as the editor types the answer... perhaps have the number change color to red when the cutoff is reached, so they don't need to even wait until save/preview.

**Comment by plexish** [comment]
Discussed in office hours: We're going switch to one field on wiki, with automatic cutoff at x characters (and a wiki-level option to place the truncation earlier).

I'm going to implement this on wiki as a css class, at some point the UI will switch over.

**Comment by plexish** [comment]
Superseded by #79

**Comment by Aprillion** [comment]
Not related to #79, same problem will happen with `See more...` as currently with `Show detailed answer`. If we want a direct link to the fully expanded answer => reopening.
e.g. <https://ui.stampy.ai/?state=7757_>
