### ISSUE TITLE
footnote styling

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#698]
Currently looks like this

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/d2df7213-4ac2-4fa3-9ba7-e3540a5efa34)

Should 
- Have no brackets around numbers
- Type class .small
- Centered to number
- 512px wide

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/6b71bc0d-9cf8-4123-b474-7b41a484c2bd)

**Comment by LeMurphant** [comment]
See also https://github.com/StampyAI/stampy-ui/issues/573
