### ISSUE TITLE
Fetch page titles dynamically in chatbot

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#713]
Ref https://github.com/StampyAI/stampy-ui/issues/668

Currently, the titles of suggested questions are hard-coded, e.g.
`  {text: 'What are large language models?', pageid: '5864'},
  {text: "Why can't we just turn the AI off if it starts to misbehave?", pageid: '3119'},
`
As discussed in Friday's meeting, it would be better to dynamically fetch the title from the pageid since the titles sometimes change.

**Comment by zarSou9** [comment]
Yes, after I made it fetch articles by pageid, Nemo also removed the questions, but its in a pending pr.
