### ISSUE TITLE
Article suggestions refresh when user clicks settings

### ISSUE THREAD

**Issue by zarSou9** [StampyAI/stampy-ui#717]
https://github.com/StampyAI/stampy-ui/assets/148247390/583b5432-7add-41fd-bc90-c597d7180777

@mruwnik This still seems to be happening on occasion. e.g. "How does the Stampy chatbot work?" consistently has this bug

**Comment by zarSou9** [comment]
It also happens on screen resize apparently:

https://github.com/StampyAI/stampy-ui/assets/148247390/dae08efa-7412-48e7-9f60-2cbe8379e2d3

This seems like a react thing which automatically updates the list which sounds very yucky

**Comment by zarSou9** [comment]
Hmm, this is still an issue. The article for "How does the Stampy chatbot work?" is a good (or i guess bad) example. @mruwnik I can have a crack at it if you would like?

**Comment by mruwnik** [comment]
give it a go
