### ISSUE TITLE
Responses automatically being upvoted

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#727]
Seems to always happen for me on desktop Safari, only for bot-generated responses.
Also sometimes happens on mobile Chrome, for bot and human responses e.g. when prompted with "Is AI smart" or "Could it be?".

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/7571f87c-3e32-427a-b6e6-0c1ef36f5db2)

![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/8bcd12aa-3b93-4d80-b838-c4fb7b0ea753)

**Comment by bryceerobertson** [comment]
This is still happening for me

**Comment by bryceerobertson** [comment]
Here's an example of it happening for me (Chrome on iPhone):
![IMG_C0354F8018B6-1](https://github.com/StampyAI/stampy-ui/assets/98026499/f434f6f5-d2eb-42de-b6c6-42a801216a44)

**Comment by zarSou9** [comment]
And you deleted your cache?
