### ISSUE TITLE
Have Subsections not show the "in progress" banner

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#753]
Ref https://github.com/StampyAI/stampy-ui/issues/560

See for instance this question that is a subsection in Coda
https://aisafety.info/questions/NLZV
![subsection](https://github.com/user-attachments/assets/0469a7b5-e39f-4228-8467-fb2ea3c1e08a)

This is relevant because in some cases we link to subsections directly, e.g.
https://aisafety.info/questions/NM1D/Careers
is linked from
https://aisafety.info/questions/8TJV/How-can-I-help

**Comment by LeMurphant** [comment]
@Aprillion Nemo says he won't be able to take this in the near term, suggested you might want to take it.

**Comment by Aprillion** [comment]
If I won't find unexpected free time between work stuff, I can have a look on Sunday...
