### ISSUE TITLE
Make all subsection pages tables

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#757]
see https://github.com/StampyAI/stampy-ui/issues/755

I suggest we implement option 4: tables everywhere
https://discord.com/channels/677546901339504640/1193299418259140690/1274983604438433852

I will discuss this with the editors, please don't start this issue yet

**Comment by LeMurphant** [comment]
Editors agree, let's do this. @Aprillion you seemed to mention "merged" on my discord thread, so if this is already done, you can just close this.

**Comment by Aprillion** [comment]
the merged reaction was about #756 - only the subsections in the help section use the table list component (since the other pages for subsections of other sections are not supposed to be reachable)

**Comment by LeMurphant** [comment]
To test them, you can find articles tagged "subsection" in coda and get their ID to put it in the URL directly
