### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#77]
Scrolling to the bottom would cause a new 10 questions to be loaded, from a pre-defined list [here](https://stampy.ai/wiki/Infinite_scroll_questions).

**Comment by Aprillion** [comment]
@plexish @ccstan99  do we want to remove footer as part of this feature? footers don't make sense with automatic infinite scrolling, it just creates frustration when you want to click a link from a footer and more stuff loads 😭 

..or we can return to #17 if we decide to keep footer

**Comment by plexish** [comment]
Probably remove, yeah. The other option would be to have it slide into view if you scroll up, like the top bar on LessWrong posts?

**Comment by plexish** [comment]
We could have Discord become a floating bottom-right icon invite
