### ISSUE TITLE
articles sections in careers page

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#781]
![Image](https://github.com/user-attachments/assets/017e5662-5199-40f9-9a83-acc177658d78)
- Just do these in the career page for now
  - For all other pages, we'll pull the articles from the relevant sub-section in Coda (they all correlate to one of the designed pages now) within the How Can I Help section.
  - We'll also need some way to group the careers articles into the three categories. Any thoughts for how to do this?
- Pull them in Coda's order
  - If the title exceeds four lines, use an ellipses at the end
  - Once the user clicks the right arrow, show 3 new articles (unless there are less than 3 to show, in which case just show 2 or 1)
    - Bonus: some sort of animation showing the cards sliding into place, rather than just instantaneously showing new cards
  - The button shown is secondary - alt. size small, so use this component
  ![Image](https://github.com/user-attachments/assets/02f4366f-546c-495f-907f-1811b47dc2b3)
  - Use the disabled state when user cannot go right or left any further (changes are: no drop shadow, and color of arrow becomes cool grey 400)
- Mobile will look like either of these, you choose
![Image](https://github.com/user-attachments/assets/85b36405-33f9-49b1-9a8f-78ad02ed6065)

**Comment by melissasamworth** [comment]
Nemo's etc for this is EOD thurs, EOD fri at latest

**Comment by melissasamworth** [comment]
@mruwnik looks great. Only issues are

- The articles are not the correct ones (work with @LeMurphant and @bryceerobertson on creating those new sections in Coda)
- Mobile is a bit off (feel free to leave this one to me, just lmk)
- ![Image](https://github.com/user-attachments/assets/da6bae0d-164d-42df-8165-a5f20838c71c)

**Comment by mruwnik** [comment]
yeah, I didn't do the css - sorry about that :/

**Comment by melissasamworth** [comment]
@mruwnik the section is pulling in the top level (the 8 heading sections) and not the individual articles inside them. We can discuss at standup tomorrow.

I'll take care of the CSS
