### ISSUE TITLE
careers page, fix padding, copy

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#783]
Bryce is going to make sure 
- all the padding on desktop page for careers matches the Figma
- all the copy matches the figma
  - also, add the copy for various testimonials (and own getting the copy)
- all the links in the link blocks link out to the right place
  - you can get the links from [the prototype](https://www.figma.com/proto/z0FHqmXksrVSnR8SIWIyOu/.info%3A-how-can-I-help%3F?node-id=6872-5905&t=HTJV8B7eqBxfORFE-1)

**Comment by bryceerobertson** [comment]
Copy is done

**Comment by bryceerobertson** [comment]
@zarSou9 how do I make external links open in a new tab? Or is this something best done by you/elsewhere in the code?

**Comment by melissasamworth** [comment]
@bryceerobertson copy is still wrong, I imagine due to merging confusion and such. Update the copy after my PR is merged and you pull it.

**Comment by zarSou9** [comment]
> @zarSou9 how do I make external links open in a new tab? Or is this something best done by you/elsewhere in the code?

I have changed the button component to automatically open external links (that start with http) in a new tab (much to @mruwnik's chagrin)

**Comment by bryceerobertson** [comment]
@melissasamworth yeah it's just done locally (that was more my personal note to self)

**Comment by melissasamworth** [comment]
@zarSou9 I think that makes sense
@bryceerobertson cool, so ETC is ~tomorrow, we can discuss at sprint
