### ISSUE TITLE
Avoid double "full list of courses"

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#828]
Mentioned in https://github.com/StampyAI/stampy-ui/pull/810

![full_list](https://github.com/user-attachments/assets/1dfbe97b-8b23-4f8f-b1ef-19553baa219d)

**Comment by mruwnik** [comment]
works for me:
![image](https://github.com/user-attachments/assets/c06953be-b86a-44fd-b1b6-739c4beab8bf)

what browser are you using?

**Comment by LeMurphant** [comment]
Looks OK now on live, must have been solved by another fix.
