### ISSUE TITLE
"Unhelpful" / thumbs down button

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#83]
Using the method from #82 to increment a counter, but additionally showing a popup asking the reader how we could have done better and posting what they say to a Discord channel #criticism in [Rob's Discord](https://discord.gg/7wjJbFJnSN) along with a link to the answer they're complaining about via Stampy.

**Comment by Aprillion** [comment]
From duplicate #289:

> Would allow for better understanding of which answers need extra attention in particular.
>
> On click the button should probably prompt for a comment by the user on how exactly the answer was unhelpful, and then remind them that they can also go into google docs to leave more granular comments about specific parts of the text if they so wish.
