### ISSUE TITLE
Question text overlaps with arrow/chevron

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-ui#86]
When screen width is narrow, sometimes the text overlaps with the arrow/chevron before wrapping to next line
<img width="595" alt="Screen Shot 2022-07-14 at 6 33 50 PM" src="https://user-images.githubusercontent.com/38997995/183771759-9c0cbdc8-6a35-409a-b25c-db18f470a00b.png">

**Comment by ChrisRimmer** [comment]
Looks like this has been (accidentally?) fixed at some time since this was opened, tested at https://ui.stampy.ai/?state=6196_

![image](https://user-images.githubusercontent.com/2526589/210599533-325d2773-84cc-4c41-8704-12fad07abc75.png)

**Comment by plexish** [comment]
It's for recessed questions only, and seems partly fixed

**Comment by plexish** [comment]
Ops, should make a new issue for that rather than re-opening.
