### ISSUE TITLE
summary produced when conversation consists only of user query

### ISSUE THREAD

**Issue by Algon-33** [StampyAI/stampy-ui#860]
From Matthew Watkins' description of the problem:

"The problem caused by the summarised conversation-thus-far that gets bundled into the prompt. Specifically, the problem is that this summary is automatically produced and included even when the conversation consists of nothing more than the user's initial query. More generally, the code is written so that the text to be summarised always includes the most recent question. So for the first question there need be no converation summary, for the second question it should be 1st question + 1st response that gets summarised (rather than 1st question + 1st response + 2nd question etc.)

The accidental inclusion of the most recent question in the text-to-be-summarised occasionally results in hallucinations like this:
Image
![image](https://github.com/user-attachments/assets/e0dd2cf7-4e3d-49ac-ab8a-4b3459650d37)

This is annoying and might cause casual users to immediately disengage after their first question. Should be very easy to fix. I managed to refactor the chat.py code myself, but couldn't test it over a multiple question/response cycle (my old laptop won't support some of the python database packages needed for that). It certainly got rid of the problem for initial queries, but I was hesitant to introduce it to the Stampy codebase until it was properly tested.

[message (2).txt](https://github.com/user-attachments/files/18008821/message.2.txt)"

**Comment by mruwnik** [comment]
should be fixed now

**Comment by LeMurphant** [comment]
Looks good.
