### ISSUE TITLE
Footnotes are too large

### ISSUE THREAD

**Issue by Algon-33** [StampyAI/stampy-ui#862]
We got some feedback people that the font for footnotes are too large. This is bad because it emphasizes the footnotes as much as the main text. Decreasing the font-size for footnotes should be fine.
![image](https://github.com/user-attachments/assets/993eec37-520d-4a34-a2a0-5152b6c66dd7)

@melissasamworth

**Comment by LeMurphant** [comment]
Fixed by https://github.com/StampyAI/stampy-ui/pull/867
