### ISSUE TITLE
Social preview for links to a single question

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#88]
e.g. ![image](https://user-images.githubusercontent.com/1039691/184558459-acbe4036-5ff0-4b6b-a45b-d8442633fb14.png)

This would be super nice for social media shares, especially once we have the copy direct link icon.

The title should be the title of the question, the body should be the first 100 characters of the answer. Ideally include " - Stampy" or " - AI Safety Info" for the respective sites in the title, but using " - Stampy's AI Safety Info" for both is ok if it's annoying to have it site-specific.

**Comment by Aprillion** [comment]
ooh, server side rendering of social preview 🤔  CF workers don't have `canvas` AFAIK, so no OG:image, but the `title` and `description` should be possible if we add a root loader in https://github.com/StampyAI/stampy-ui/blob/42ad8c6ac623f625f2381d128ccd30425de9186b/app/root.tsx
