### ISSUE TITLE
Add css for redlinks

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#89]
Currently if a page is redlinked in the wiki it shows up as a normal link in the UI. e.g. Conjecture [here](https://ui.stampy.ai/?state=8264_)

**Comment by Aprillion** [comment]
What is the desired style, actually red color or something different?

**Comment by plexish** [comment]
Yes, the same red as in-wiki redlinks: https://stampy.ai/wiki/What_training_programs_and_courses_are_available_for_AGI_safety%3F

**Comment by mruwnik** [comment]
wouldn't it maybe be better to simply remove unresolving links from the UI?

**Comment by plexish** [comment]
@Aprillion What do you mean by
> the page from first comment in gdocs

But, there won't be redlinks, no, so closing this.

**Comment by Aprillion** [comment]
@plexish I was trying to ask whether https://ui.stampy.ai/?state=8264_ has been migrated from https://stampy.ai/wiki/Plex%27s_Answer_to_What_training_programs_and_courses_are_available_for_AGI_safety%3F to GDocs yet...

It's not in Coda [yet](https://coda.io/apis/v1/docs/fau7sl2hmG/tables/Answers/rows?useColumnNames=true&sortBy=natural&valueFormat=rich&query=%22Name%22:%22Answer%20to%20What%20training%20programs%20and%20courses%20are%20available%20for%20AGI%20safety?%22), so either not migrated to GDocs yet or else there was a problem fetching it from GDocs to Coda that might be worth reporting to Chris (or else it's a known issue one way or another and I will find our how the new version without "redlink" will look like at some later time, after someone fixes something somewhere).

**Comment by plexish** [comment]
Huh, it looks like it is in coda? 
![image](https://user-images.githubusercontent.com/1039691/213944187-a81936db-8d26-4bca-86a7-7ea27f3c2903.png)
Not sure why that query isn't finding it

**Comment by Aprillion** [comment]
oh, right, I was searching for title "Answer to ..." copy&pasted from wiki of the answer page instead of the question title 🤦‍♂️

currently [https://stampy-ui.aprillion.workers.dev/?state=8264_] is without formatting
