### ISSUE TITLE
Use `defer` in remix loader instead of fetching from `useEffect`

### ISSUE THREAD

**Issue by Aprillion** [StampyAI/stampy-ui#94]
We load low priority data by using `fetch('/questions/allCanonicallyAnswered')` in a `useEffect` in https://github.com/StampyAI/stampy-ui/blob/master/app/hooks/useQuestionStateInUrl.ts#L40

I got some tips from Kent in https://youtu.be/0VgyPIRHZl8?t=2457 (starting 41:00)

Since CF Workers support streaming responses, we can send low priority data from a loader without blocking the initial screen:
https://github.com/kentcdodds/advanced-remix/blob/main/final/09-defer/app/routes/__app/sales/customers/%24customerId.tsx

Let's update our code to load the data as soon as possible without blocking initial SSR render, without waiting for client-side `useEffect` - `defer` looks like the best solution (we also have to update to React 18, hopefully all hydration issues will be resolved).

**Comment by plexish** [comment]
Is this done @Aprillion?

**Comment by Aprillion** [comment]
Not done, but I'm actually happy with fetching from useEffect, not missing any features provided by `defer`, so let's close this one and if we need to use it for some feature/bugfix we can use it later.
