### ISSUE TITLE
Link button should copy to clipboard

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-ui#97]
Clicking on "Link" icon button should copy the link to clipboard instead of going directly to the page.

**Comment by plexish** [comment]
Maybe give a little visual indication that this has happened too? Saying "Link copied to clipboard"?

**Comment by Aprillion** [comment]
Left click will now (in the PR) copy the link, while it's still possible to use context menu or middle mouse button to open the link on new tab. Same confirmation as for the `Share link` header icon, I changed the message to "Link copied to clipboard" for both.
